defmodule :"Elixir.Thunderline.Repo.Migrations.Domains=Thunderline.Thunderblock.Domain,Thunderline.Thunderbolt.Domain,Thunderline.Thundergrid.Domain,Thunderline.Thunderflow.Domain,Thunderline.Thunderlink.Domain,Thundergate.Domain,Thundercrown.Domain" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :hashed_password, :text, null: true
      add :password, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      remove :password
      modify :hashed_password, :text, null: false
    end
  end
end
