defmodule Thunderline.Thunderlink.Resources.Ticket do
  @moduledoc """
  Simple ticket resource following the Ash getting started guide.

  Using ETS data layer for initial testing before moving to PostgreSQL.
  """

  # This turns this module into a resource using Postgres data layer for AshOban triggers
  use Ash.Resource,
    domain: Thunderline.Thunderlink.Domain,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshOban, AshGraphql.Resource],
    authorizers: [Ash.Policy.Authorizer]

  require Ash.Query

  postgres do
    table "support_tickets"
    repo Thunderline.Repo
  end

  graphql do
    type :ticket
  end

  actions do
    # Use the default implementation of the :read action
    defaults [:read]

    # Create action for opening tickets
    create :open do
      accept [:subject]
    end

    # Update action for closing tickets
    update :close do
      # We don't want to accept any input here
      accept []

      validate attribute_does_not_equal(:status, :closed) do
        message "Ticket is already closed"
      end

      change set_attribute(:status, :closed)
      change set_attribute(:closed_at, &DateTime.utc_now/0)
    end

    # Action to process tickets in background
    update :process do
      accept []

      validate attribute_equals(:status, :open) do
        message "Only open tickets can be processed"
      end

      change set_attribute(:status, :processing)
      change set_attribute(:processed_at, &DateTime.utc_now/0)
    end

    # Action for automatic escalation
    update :escalate do
      accept []

      change set_attribute(:escalated, true)
      change set_attribute(:escalated_at, &DateTime.utc_now/0)
    end
  end

  # Authorization policies - CRITICAL for AshOban to work
  policies do
    # Allow AshOban to bypass authorization for background jobs
    bypass AshOban.Checks.AshObanInteraction do
      authorize_if always()
    end

    # Default policy for regular access
    policy always() do
      authorize_if always()
    end
  end

  # AshOban configuration with working triggers
  oban do
    triggers do
      # Process open tickets every minute
      trigger :process_tickets do
        action :process
        where expr(status == :open and is_nil(processed_at))
        scheduler_cron "* * * * *"  # Every minute
        queue :default
        max_attempts 3
      end

      # Escalate tickets that haven't been processed in 5 minutes
      trigger :escalate_tickets do
        action :escalate
        where expr(
          status == :open and
          not escalated and
          inserted_at < ago(5, :minute)
        )
        scheduler_cron "*/2 * * * *"  # Every 2 minutes
        queue :scheduled_workflows
        max_attempts 2
      end
    end
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :subject, :string do
      # Don't allow `nil` values
      allow_nil? false
      # Allow this attribute to be public. By default, all attributes are private.
      public? true
    end

    # status is either `open` or `closed`. We can add more statuses later
    attribute :status, :atom do
      # Constraints allow you to provide extra rules for the value.
      # The available constraints depend on the type
      # Since atoms are generally only used when we know all of the values
      # it provides a `one_of` constraint, that only allows those values
      constraints [one_of: [:open, :processing, :closed]]

      # The status defaulting to open makes sense
      default :open

      # We also don't want status to ever be `nil`
      allow_nil? false
    end

    # Escalation flag
    attribute :escalated, :boolean do
      default false
    end

    # Timestamps for tracking processing
    attribute :processed_at, :utc_datetime_usec
    attribute :escalated_at, :utc_datetime_usec
    attribute :closed_at, :utc_datetime_usec

    # Auto-managed timestamps
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end
end
