# Unikernel Prototype (skeleton)

.PHONY: image run-kvm clean

image:
	@echo "Build unikernel image (Unikraft/Nanos) here"

run-kvm:
	@echo "Run unikernel under KVM here"

clean:
	@echo "Cleanup artifacts"
