defmodule Thunderline.Repo.Migrations.InitThunderline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:thunderbolts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :bounds_max_z, :decimal
      add :bounds_max_y, :decimal
      add :bounds_max_x, :decimal
      add :bounds_min_z, :decimal
      add :bounds_min_y, :decimal
      add :bounds_min_x, :decimal
      add :processing_latency_ms, :bigint
      add :last_heartbeat, :utc_datetime_usec
      add :load_factor, :decimal
      add :status, :text
      add :thunderbit_count, :bigint
      add :capacity, :bigint
      add :position_z, :decimal
      add :position_y, :decimal
      add :position_x, :decimal
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:thunderbolts, [:position_x, :position_y, :position_z],
             name: "thunderbolts_position_index"
           )

    create table(:thunderbits, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :domain_actions, :map, default: %{}
      add :ecs_entity_id, :text
      add :processing_latency_ms, :bigint
      add :task_queue_size, :bigint
      add :energy_level, :bigint
      add :velocity_z, :decimal
      add :velocity_y, :decimal
      add :velocity_x, :decimal
      add :position_z, :decimal
      add :position_y, :decimal
      add :position_x, :decimal
      add :status, :text

      add :thunderbolt_id,
          references(:thunderbolts,
            column: :id,
            name: "thunderbits_thunderbolt_id_fkey",
            type: :uuid
          ),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:thunderbits, "thunderbits_thunderbolt_id_fkey")

    drop table(:thunderbits)

    drop_if_exists unique_index(:thunderbolts, [:position_x, :position_y, :position_z],
                     name: "thunderbolts_position_index"
                   )

    drop table(:thunderbolts)
  end
end
