defmodule Thunderline.Thunderbolt.RAG.Document do
  @moduledoc """
  RAG Document resource with automatic vectorization.

  Stores text documents with automatic embedding generation using ash_ai.
  Provides semantic search capabilities via vector similarity.

  ## Features

  - **Automatic vectorization**: Content is embedded on create/update
  - **Semantic search**: Vector similarity search with cosine distance
  - **Metadata support**: Store arbitrary metadata (source, author, etc.)
  - **Manual control**: Update embeddings on demand via :update_embeddings action

  ## Examples

      # Ingest a document
      {:ok, doc} = Thunderline.Thunderbolt.RAG.create_document!(%{
        content: "ThunderBolt handles ML compute and inference.",
        metadata: %{source: "README.md", section: "Architecture"}
      })

      # Semantic search
      results = Thunderline.Thunderbolt.RAG.semantic_search!("What does ThunderBolt do?")
  """
  use Ash.Resource,
    domain: Thunderline.Thunderbolt.Domain,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshAi]

  require Logger
  require Ash.Query

  postgres do
    table "rag_documents"
    repo Thunderline.Repo
  end

  vectorize do
    full_text do
      text fn record -> record.content end
      used_attributes [:content]
    end

    strategy :manual
    embedding_model Thunderline.Thunderbolt.RAG.EmbeddingModel
  end

  # Authorization - allow all for MVP (add policies later)
  code_interface do
    define :create_document, action: :create
    define :list_documents, action: :read
    define :get_document, action: :read, get_by: [:id]
    define :update_document, action: :update
    define :delete_document, action: :destroy
    define :update_embeddings, action: :ash_ai_update_embeddings
    define :semantic_search, action: :semantic_search, args: [:query]
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      accept [:content, :metadata]
      description "Create a document (embeddings computed on demand)"
    end

    update :update do
      accept [:content, :metadata]
      description "Update document content/metadata"
    end

    # ash_ai automatically generates :ash_ai_update_embeddings
    # We can use it directly for manual embedding updates

    read :semantic_search do
      description "Search documents by semantic similarity to query"

      argument :query, :string do
        allow_nil? false
        description "Natural language search query"
      end

      argument :limit, :integer do
        default 5
        constraints min: 1, max: 50
        description "Maximum results to return"
      end

      argument :threshold, :float do
        default 0.5
        constraints min: 0.0, max: 1.0
        description "Maximum cosine distance (0=identical, 1=opposite)"
      end

      prepare fn query, _context ->
        query_text = query.arguments[:query]
        limit = query.arguments[:limit] || 5
        threshold = query.arguments[:threshold] || 0.5

        Logger.info("[RAG.Document] Semantic search: \"#{query_text}\" (limit=#{limit})")

        # Generate embedding for query
        case Thunderline.Thunderbolt.RAG.EmbeddingModel.generate([query_text], []) do
          {:ok, [search_vector]} ->
            Logger.debug(
              "[RAG.Document] Generated query embedding (#{length(search_vector)} dims)"
            )

            # Filter by cosine distance and sort by relevance
            # Using PostgreSQL's <=> operator for cosine distance
            # Note: Must explicitly cast array to vector type for PostgreSQL
            query
            |> Ash.Query.filter(
              expr(fragment("(? <=> ?::vector)", full_text_vector, ^search_vector) < ^threshold)
            )
            |> Ash.Query.sort(
              {calc(fragment("(? <=> ?::vector)", full_text_vector, ^search_vector),
                 type: :float
               ), :asc}
            )
            |> Ash.Query.limit(limit)

          {:error, error} ->
            Logger.error("[RAG.Document] Failed to generate query embedding: #{inspect(error)}")
            Ash.Query.add_error(query, "Failed to generate embedding: #{inspect(error)}")
        end
      end
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :content, :string do
      allow_nil? false
      constraints max_length: 100_000
      description "Document text content to be embedded and searched"
    end

    attribute :metadata, :map do
      default %{}
      description "Arbitrary metadata (source, author, tags, etc.)"
    end

    # full_text_vector is auto-generated by ash_ai vectorize
    # Type: vector(384) for sentence-transformers/all-MiniLM-L6-v2

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end
end
