import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure the AshPostgres repo
db_url = System.get_env("DATABASE_URL")

dev_repo_defaults = [
  username: System.get_env("PGUSER", "postgres"),
  password: System.get_env("PGPASSWORD", "postgres"),
  hostname: System.get_env("PGHOST", "127.0.0.1"),
  database: System.get_env("PGDATABASE", "thunderline"),
  port: System.get_env("PGPORT", "5432") |> String.to_integer(),
  pool_size: 10,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  socket_options: [:inet],
  connect_timeout: 60_000,
  pool_timeout: 60_000,
  ownership_timeout: 60_000
]

# Allow DATABASE_URL to fully override discrete settings if provided.
repo_config =
  if db_url do
    Keyword.put(dev_repo_defaults, :url, db_url)
  else
    dev_repo_defaults
  end

config :thunderline, Thunderline.Repo, repo_config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :thunderline, ThunderlineWeb.Endpoint,
  # Bind IP is configurable so you can reach the dev server from outside a container/VM:
  #   BIND_ALL=1 mix phx.server  -> binds 0.0.0.0
  # Otherwise defaults to loopback only (127.0.0.1) for safety.
  http: [
    ip:
      if(System.get_env("BIND_ALL") in ["1", "true", "TRUE"],
        do: {0, 0, 0, 0},
        else: {127, 0, 0, 1}
      ),
    port: System.get_env("PORT", "4000") |> String.to_integer()
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "development_secret_key_base_that_is_at_least_64_bytes_long_for_security",
  # Esbuild removed (no Node/bundling). Tailwind binary only.
  watchers: [
    tailwind: {Tailwind, :install_and_run, [:thunderline, ~w(--watch)]},
    esbuild: {Esbuild, :install_and_run, [:thunderline, ~w(--sourcemap=inline --watch)]}
  ]

# Development feature flags (compile-time for Feature module)
config :thunderline, :features, ca_viz: true, ai_chat_panel: true, tocp: false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :thunderline, ThunderlineWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/thunderline_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/thunderline_web/templates/.*(eex)$"
    ]
  ]

# Market ingest mock logging throttle (adjust MARKET_INGEST_LOG_EVERY env to override)
config :thunderline, :market_ingest, log_every: 50

# Enable dev routes for dashboard and mailbox
config :thunderline, dev_routes: true, token_signing_secret: "vadctdmv/MrdcKdJvG1Bl3woZoYMGKXL"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Thunderwatch (internal file watcher) configuration
config :thunderline, :thunderwatch,
  enabled: true,
  roots: ["lib"],
  ignore: [~r{/\.git/}, ~r{/deps/}, ~r{/priv/static/}],
  hash?: false,
  max_events: 2_000

# Market ingest (mock) logging controls
config :thunderline, :market_ingest,
  log_every: String.to_integer(System.get_env("MARKET_INGEST_LOG_EVERY", "50")),
  log_payload?: System.get_env("MARKET_INGEST_LOG_PAYLOAD", "false") in ["1", "true", "TRUE"],
  producer_log?: System.get_env("MARKET_INGEST_PRODUCER_LOG", "false") in ["1", "true", "TRUE"]
