defmodule Thunderline.Repo.Migrations.CerebrosTrainingPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:document_uploads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stage, :bigint, null: false
      add :filename, :text, null: false
      add :file_url, :text
      add :content, :text
      add :labels, {:array, :text}, default: []
      add :chunk_count, :bigint, default: 0
      add :processed, :boolean, default: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :training_dataset_id, :uuid, null: false
    end

    create table(:training_datasets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:document_uploads) do
      modify :training_dataset_id,
             references(:training_datasets,
               column: :id,
               name: "document_uploads_training_dataset_id_fkey",
               type: :uuid,
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:training_datasets) do
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "collecting"
      add :stage_1_count, :bigint, default: 0
      add :stage_2_count, :bigint, default: 0
      add :stage_3_count, :bigint, default: 0
      add :stage_4_count, :bigint, default: 0
      add :total_chunks, :bigint, default: 0
      add :corpus_path, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:thunderline_events) do
      add :changed_attributes, :map, null: false, default: %{}
    end

    create table(:cerebros_training_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :cerebros_job_id, :text
      add :status, :text, null: false, default: "queued"
      add :phase, :bigint, default: 0
      add :checkpoint_urls, {:array, :text}, default: []
      add :current_checkpoint_url, :text
      add :metrics, :map, default: %{}
      add :error_message, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :model_loaded, :boolean, default: false
      add :model_format, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :training_dataset_id,
          references(:training_datasets,
            column: :id,
            name: "cerebros_training_jobs_training_dataset_id_fkey",
            type: :uuid,
            on_delete: :nilify_all,
            on_update: :update_all
          ), null: false
    end
  end

  def down do
    drop constraint(:cerebros_training_jobs, "cerebros_training_jobs_training_dataset_id_fkey")

    drop table(:cerebros_training_jobs)

    alter table(:thunderline_events) do
      remove :changed_attributes
    end

    alter table(:training_datasets) do
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :corpus_path
      remove :total_chunks
      remove :stage_4_count
      remove :stage_3_count
      remove :stage_2_count
      remove :stage_1_count
      remove :status
      remove :description
      remove :name
    end

    drop constraint(:document_uploads, "document_uploads_training_dataset_id_fkey")

    alter table(:document_uploads) do
      modify :training_dataset_id, :uuid
    end

    drop table(:training_datasets)

    drop table(:document_uploads)
  end
end
