defmodule Thunderline.Repo.Migrations.HcDeltaOrchestration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:policy_evaluations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :policy_id, :uuid
      add :policy_name, :text, null: false
      add :actor_id, :text
      add :tenant_id, :text
      add :action_descriptor, :map, null: false, default: %{}
      add :context_snapshot, :map, null: false, default: %{}
      add :rule_results, :map, null: false, default: %{}
      add :verdict, :text, null: false
      add :verdict_reason, :text
      add :duration_us, :bigint
      add :evaluated_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderpac_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text, null: false, default: "assistant"
      add :description, :text
      add :capabilities, {:array, :text}, null: false, default: []
      add :constraints, :map, null: false, default: %{}
      add :persona_overlay, :map, null: false, default: %{}
      add :priority, :bigint, null: false, default: 50
      add :is_system, :boolean, null: false, default: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "CREATE INDEX pac_roles_caps_idx ON thunderpac_roles USING GIN (capabilities)"

    create index(:thunderpac_roles, [:is_system], name: "pac_roles_system_idx")

    create index(:thunderpac_roles, [:category], name: "pac_roles_category_idx")

    create unique_index(:thunderpac_roles, [:name], name: "thunderpac_roles_unique_name_index")

    create table(:behavior_graphs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :graph_data, :map, null: false, default: %{}
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "active"
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:behavior_graphs, [:name, :version],
             name: "behavior_graphs_unique_name_version_index"
           )

    create table(:thunderpac_intents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "pending"
      add :intent_type, :text, null: false
      add :priority, :bigint, null: false, default: 50
      add :payload, :map, null: false, default: %{}
      add :result, :map
      add :error, :text
      add :retry_count, :bigint, null: false, default: 0
      add :max_retries, :bigint, null: false, default: 3
      add :energy_cost, :bigint, null: false, default: 1
      add :scheduled_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :timeout_ms, :bigint, null: false, default: 30000
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pac_id, :uuid, null: false
      add :role_id, :uuid
      add :parent_intent_id, :uuid
    end

    create index(:thunderpac_intents, [:scheduled_at], name: "pac_intents_scheduled_idx")

    create index(:thunderpac_intents, [:intent_type], name: "pac_intents_type_idx")

    create index(:thunderpac_intents, [:priority], name: "pac_intents_priority_idx")

    create index(:thunderpac_intents, [:state], name: "pac_intents_state_idx")

    create index(:thunderpac_intents, [:pac_id], name: "pac_intents_pac_idx")

    # NOTE: saga_states table creation removed - already created by earlier migration
    # 20251128234500_add_saga_states.exs

    create table(:thunderoll_experiments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :base_model_ref, :text
      add :rank, :bigint, null: false, default: 1
      add :population_size, :bigint, null: false
      add :sigma, :float, null: false, default: 0.02
      add :max_generations, :bigint, null: false, default: 100
      add :fitness_spec, :map, null: false, default: %{}
      add :convergence_criteria, :map, null: false, default: %{}
      add :backend, :text, null: false, default: "nx_native"
      add :status, :text, null: false, default: "pending"
      add :current_generation, :bigint, null: false, default: 0
      add :final_fitness, :float
      add :total_evaluations, :bigint
      add :error_message, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:thunderoll_experiments, [:inserted_at],
             name: "thunderoll_experiments_created_idx"
           )

    create index(:thunderoll_experiments, [:base_model_ref],
             name: "thunderoll_experiments_model_idx"
           )

    create index(:thunderoll_experiments, [:status], name: "thunderoll_experiments_status_idx")

    create table(:thunderpac_traits_evolution_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :tpe_params, :map, null: false, default: %{}
      add :fitness_window_ms, :bigint, null: false, default: 300_000
      add :evolution_profile, :text, null: false, default: "balanced"
      add :max_iterations, :bigint, null: false, default: 50
      add :convergence_threshold, :float, null: false, default: 0.01
      add :reflex_events_count, :bigint, null: false, default: 0
      add :initial_traits, {:array, :float}
      add :result, :map
      add :error_message, :text
      add :metrics_summary, :map
      add :iteration_count, :bigint, null: false, default: 0
      add :best_fitness, :float
      add :fitness_history, {:array, :float}, null: false, default: []
      add :scheduled_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :priority, :bigint, null: false, default: 1
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "pending"
      add :pac_id, :uuid, null: false
    end

    create index(:thunderpac_traits_evolution_jobs, [:completed_at],
             name: "traits_evolution_jobs_completed_idx"
           )

    create index(:thunderpac_traits_evolution_jobs, [:scheduled_at],
             name: "traits_evolution_jobs_scheduled_idx"
           )

    create index(:thunderpac_traits_evolution_jobs, [:pac_id],
             name: "traits_evolution_jobs_pac_idx"
           )

    create index(:thunderpac_traits_evolution_jobs, [:status],
             name: "traits_evolution_jobs_status_idx"
           )

    create table(:graph_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :initial_context, :map, null: false, default: %{}
      add :final_context, :map
      add :node_results, :map, null: false, default: %{}
      add :error_details, :map
      add :triggered_by, :text
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :behavior_graph_id,
          references(:behavior_graphs,
            column: :id,
            name: "graph_executions_behavior_graph_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create table(:thunderpac_memory_cells, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :memory_type, :text, null: false, default: "episodic"
      add :content, :map, null: false, default: %{}
      add :salience, :float, null: false, default: 0.5
      add :tags, {:array, :text}, null: false, default: []
      add :access_count, :bigint, null: false, default: 0
      add :last_accessed_at, :utc_datetime_usec
      add :decay_at, :utc_datetime_usec, null: false
      add :consolidated_from, {:array, :uuid}, null: false, default: []
      add :context, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pac_id, :uuid, null: false
    end

    execute "CREATE INDEX memory_cells_tags_idx ON thunderpac_memory_cells USING GIN (tags)"

    execute "CREATE INDEX memory_cells_content_idx ON thunderpac_memory_cells USING GIN (content)"

    create index(:thunderpac_memory_cells, [:pac_id, :memory_type, :salience],
             name: "memory_cells_pac_type_salience_idx"
           )

    create index(:thunderpac_memory_cells, [:pac_id, :salience],
             name: "memory_cells_pac_salience_idx"
           )

    create index(:thunderpac_memory_cells, [:decay_at], name: "memory_cells_decay_idx")

    create index(:thunderpac_memory_cells, [:salience], name: "memory_cells_salience_idx")

    create index(:thunderpac_memory_cells, [:memory_type], name: "memory_cells_type_idx")

    create index(:thunderpac_memory_cells, [:pac_id], name: "memory_cells_pac_idx")

    create table(:policy_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :policy_data, :map, null: false, default: %{}
      add :applies_to, :map, null: false
      add :priority, :bigint, null: false, default: 100
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "active"
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:policy_definitions, [:name, :version],
             name: "policy_definitions_unique_name_version_index"
           )

    # NOTE: upm_observations columns already added by 20251126124200_add_manifold_clustering_fields
    # alter table(:upm_observations) do ... end removed

    create table(:thunderpac_pacs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderpac_intents) do
      modify :pac_id,
             references(:thunderpac_pacs,
               column: :id,
               name: "thunderpac_intents_pac_id_fkey",
               type: :uuid
             )

      modify :role_id,
             references(:thunderpac_roles,
               column: :id,
               name: "thunderpac_intents_role_id_fkey",
               type: :uuid
             )

      modify :parent_intent_id,
             references(:thunderpac_intents,
               column: :id,
               name: "thunderpac_intents_parent_intent_id_fkey",
               type: :uuid
             )
    end

    alter table(:thunderpac_traits_evolution_jobs) do
      modify :pac_id,
             references(:thunderpac_pacs,
               column: :id,
               name: "thunderpac_traits_evolution_jobs_pac_id_fkey",
               type: :uuid,
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:thunderpac_memory_cells) do
      modify :pac_id,
             references(:thunderpac_pacs,
               column: :id,
               name: "thunderpac_memory_cells_pac_id_fkey",
               type: :uuid,
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:thunderpac_pacs) do
      add :name, :text, null: false
      add :status, :text, null: false, default: "seed"
      add :persona, :map, null: false, default: %{}
      add :memory_state, :map, null: false, default: %{}
      add :trait_vector, {:array, :float}, null: false, default: []
      add :intent_queue, {:array, :map}, null: false, default: []
      add :capabilities, {:array, :text}, null: false, default: []
      add :last_active_at, :utc_datetime_usec
      add :total_active_ticks, :bigint, null: false, default: 0
      add :session_count, :bigint, null: false, default: 0
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "seed"

      add :identity_kernel_id,
          references(:identity_kernels,
            column: :id,
            name: "thunderpac_pacs_identity_kernel_id_fkey",
            type: :uuid,
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :active_role_id,
          references(:thunderpac_roles,
            column: :id,
            name: "thunderpac_pacs_active_role_id_fkey",
            type: :uuid,
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    execute "CREATE INDEX pacs_traits_idx ON thunderpac_pacs USING GIN (trait_vector)"

    execute "CREATE INDEX pacs_memory_idx ON thunderpac_pacs USING GIN (memory_state)"

    execute "CREATE INDEX pacs_persona_idx ON thunderpac_pacs USING GIN (persona)"

    create index(:thunderpac_pacs, [:last_active_at], name: "pacs_last_active_idx")

    create index(:thunderpac_pacs, [:active_role_id], name: "pacs_role_idx")

    create index(:thunderpac_pacs, [:identity_kernel_id], name: "pacs_identity_idx")

    create index(:thunderpac_pacs, [:status], name: "pacs_status_idx")

    create unique_index(:thunderpac_pacs, [:name], name: "thunderpac_pacs_unique_name_index")

    create table(:thunderoll_generations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :index, :bigint, null: false
      add :fitness_stats, :map
      add :best_fitness, :float
      add :population_summary, :map
      add :update_delta_ref, :text
      add :duration_ms, :bigint
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id,
          references(:thunderoll_experiments,
            column: :id,
            name: "thunderoll_generations_experiment_id_fkey",
            type: :uuid,
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:thunderoll_generations, [:experiment_id],
             name: "thunderoll_generations_experiment_idx"
           )

    create index(:thunderoll_generations, [:experiment_id, :index],
             name: "thunderoll_generations_exp_idx_unique",
             unique: true
           )

    create table(:thunderpac_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :snapshot_type, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :state_data, :map, null: false, default: %{}
      add :compressed, :boolean, null: false, default: false
      add :checksum, :text
      add :size_bytes, :bigint
      add :trigger, :text
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pac_id,
          references(:thunderpac_pacs,
            column: :id,
            name: "thunderpac_states_pac_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create index(:thunderpac_states, [:inserted_at], name: "pac_states_time_idx")

    create index(:thunderpac_states, [:snapshot_type], name: "pac_states_type_idx")

    create index(:thunderpac_states, [:pac_id], name: "pac_states_pac_idx")

    create table(:thunderwall_sandbox_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :operation_type, :text, null: false
      add :target_type, :text, null: false
      add :target_id, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :params, :map, null: false, default: %{}
      add :result, :map, null: false, default: %{}
      add :triggered_by, :text
      add :reason, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :error_details, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "CREATE INDEX sandbox_logs_result_idx ON thunderwall_sandbox_logs USING GIN (result)"

    execute "CREATE INDEX sandbox_logs_params_idx ON thunderwall_sandbox_logs USING GIN (params)"

    create index(:thunderwall_sandbox_logs, [:expires_at], name: "sandbox_logs_expires_idx")

    create index(:thunderwall_sandbox_logs, [:started_at], name: "sandbox_logs_started_idx")

    create index(:thunderwall_sandbox_logs, [:target_type, :target_id],
             name: "sandbox_logs_target_idx"
           )

    create index(:thunderwall_sandbox_logs, [:status], name: "sandbox_logs_status_idx")

    create index(:thunderwall_sandbox_logs, [:operation_type], name: "sandbox_logs_type_idx")
  end

  def down do
    drop_if_exists index(:thunderwall_sandbox_logs, [:operation_type],
                     name: "sandbox_logs_type_idx"
                   )

    drop_if_exists index(:thunderwall_sandbox_logs, [:status], name: "sandbox_logs_status_idx")

    drop_if_exists index(:thunderwall_sandbox_logs, [:target_type, :target_id],
                     name: "sandbox_logs_target_idx"
                   )

    drop_if_exists index(:thunderwall_sandbox_logs, [:started_at],
                     name: "sandbox_logs_started_idx"
                   )

    drop_if_exists index(:thunderwall_sandbox_logs, [:expires_at],
                     name: "sandbox_logs_expires_idx"
                   )

    execute "DROP INDEX IF EXISTS sandbox_logs_params_idx"

    execute "DROP INDEX IF EXISTS sandbox_logs_result_idx"

    drop table(:thunderwall_sandbox_logs)

    drop constraint(:thunderpac_states, "thunderpac_states_pac_id_fkey")

    drop_if_exists index(:thunderpac_states, [:pac_id], name: "pac_states_pac_idx")

    drop_if_exists index(:thunderpac_states, [:snapshot_type], name: "pac_states_type_idx")

    drop_if_exists index(:thunderpac_states, [:inserted_at], name: "pac_states_time_idx")

    drop table(:thunderpac_states)

    drop constraint(:thunderoll_generations, "thunderoll_generations_experiment_id_fkey")

    drop_if_exists index(:thunderoll_generations, [:experiment_id, :index],
                     name: "thunderoll_generations_exp_idx_unique"
                   )

    drop_if_exists index(:thunderoll_generations, [:experiment_id],
                     name: "thunderoll_generations_experiment_idx"
                   )

    drop table(:thunderoll_generations)

    drop_if_exists unique_index(:thunderpac_pacs, [:name],
                     name: "thunderpac_pacs_unique_name_index"
                   )

    drop constraint(:thunderpac_pacs, "thunderpac_pacs_identity_kernel_id_fkey")

    drop constraint(:thunderpac_pacs, "thunderpac_pacs_active_role_id_fkey")

    drop_if_exists index(:thunderpac_pacs, [:status], name: "pacs_status_idx")

    drop_if_exists index(:thunderpac_pacs, [:identity_kernel_id], name: "pacs_identity_idx")

    drop_if_exists index(:thunderpac_pacs, [:active_role_id], name: "pacs_role_idx")

    drop_if_exists index(:thunderpac_pacs, [:last_active_at], name: "pacs_last_active_idx")

    execute "DROP INDEX IF EXISTS pacs_persona_idx"

    execute "DROP INDEX IF EXISTS pacs_memory_idx"

    execute "DROP INDEX IF EXISTS pacs_traits_idx"

    alter table(:thunderpac_pacs) do
      remove :active_role_id
      remove :identity_kernel_id
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :session_count
      remove :total_active_ticks
      remove :last_active_at
      remove :capabilities
      remove :intent_queue
      remove :trait_vector
      remove :memory_state
      remove :persona
      remove :status
      remove :name
    end

    drop constraint(:thunderpac_memory_cells, "thunderpac_memory_cells_pac_id_fkey")

    alter table(:thunderpac_memory_cells) do
      modify :pac_id, :uuid
    end

    drop constraint(
           :thunderpac_traits_evolution_jobs,
           "thunderpac_traits_evolution_jobs_pac_id_fkey"
         )

    alter table(:thunderpac_traits_evolution_jobs) do
      modify :pac_id, :uuid
    end

    drop constraint(:thunderpac_intents, "thunderpac_intents_pac_id_fkey")

    drop constraint(:thunderpac_intents, "thunderpac_intents_role_id_fkey")

    drop constraint(:thunderpac_intents, "thunderpac_intents_parent_intent_id_fkey")

    alter table(:thunderpac_intents) do
      modify :parent_intent_id, :uuid
      modify :role_id, :uuid
      modify :pac_id, :uuid
    end

    drop table(:thunderpac_pacs)

    # NOTE: upm_observations columns managed by 20251126124200_add_manifold_clustering_fields
    # drop + alter removed

    drop_if_exists unique_index(:policy_definitions, [:name, :version],
                     name: "policy_definitions_unique_name_version_index"
                   )

    drop table(:policy_definitions)

    drop_if_exists index(:thunderpac_memory_cells, [:pac_id], name: "memory_cells_pac_idx")

    drop_if_exists index(:thunderpac_memory_cells, [:memory_type], name: "memory_cells_type_idx")

    drop_if_exists index(:thunderpac_memory_cells, [:salience], name: "memory_cells_salience_idx")

    drop_if_exists index(:thunderpac_memory_cells, [:decay_at], name: "memory_cells_decay_idx")

    drop_if_exists index(:thunderpac_memory_cells, [:pac_id, :salience],
                     name: "memory_cells_pac_salience_idx"
                   )

    drop_if_exists index(:thunderpac_memory_cells, [:pac_id, :memory_type, :salience],
                     name: "memory_cells_pac_type_salience_idx"
                   )

    execute "DROP INDEX IF EXISTS memory_cells_content_idx"

    execute "DROP INDEX IF EXISTS memory_cells_tags_idx"

    drop table(:thunderpac_memory_cells)

    drop constraint(:graph_executions, "graph_executions_behavior_graph_id_fkey")

    drop table(:graph_executions)

    drop_if_exists index(:thunderpac_traits_evolution_jobs, [:status],
                     name: "traits_evolution_jobs_status_idx"
                   )

    drop_if_exists index(:thunderpac_traits_evolution_jobs, [:pac_id],
                     name: "traits_evolution_jobs_pac_idx"
                   )

    drop_if_exists index(:thunderpac_traits_evolution_jobs, [:scheduled_at],
                     name: "traits_evolution_jobs_scheduled_idx"
                   )

    drop_if_exists index(:thunderpac_traits_evolution_jobs, [:completed_at],
                     name: "traits_evolution_jobs_completed_idx"
                   )

    drop table(:thunderpac_traits_evolution_jobs)

    drop_if_exists index(:thunderoll_experiments, [:status],
                     name: "thunderoll_experiments_status_idx"
                   )

    drop_if_exists index(:thunderoll_experiments, [:base_model_ref],
                     name: "thunderoll_experiments_model_idx"
                   )

    drop_if_exists index(:thunderoll_experiments, [:inserted_at],
                     name: "thunderoll_experiments_created_idx"
                   )

    drop table(:thunderoll_experiments)

    # NOTE: saga_states drops removed - table managed by 20251128234500_add_saga_states.exs

    drop_if_exists index(:thunderpac_intents, [:pac_id], name: "pac_intents_pac_idx")

    drop_if_exists index(:thunderpac_intents, [:state], name: "pac_intents_state_idx")

    drop_if_exists index(:thunderpac_intents, [:priority], name: "pac_intents_priority_idx")

    drop_if_exists index(:thunderpac_intents, [:intent_type], name: "pac_intents_type_idx")

    drop_if_exists index(:thunderpac_intents, [:scheduled_at], name: "pac_intents_scheduled_idx")

    drop table(:thunderpac_intents)

    drop_if_exists unique_index(:behavior_graphs, [:name, :version],
                     name: "behavior_graphs_unique_name_version_index"
                   )

    drop table(:behavior_graphs)

    drop_if_exists unique_index(:thunderpac_roles, [:name],
                     name: "thunderpac_roles_unique_name_index"
                   )

    drop_if_exists index(:thunderpac_roles, [:category], name: "pac_roles_category_idx")

    drop_if_exists index(:thunderpac_roles, [:is_system], name: "pac_roles_system_idx")

    execute "DROP INDEX IF EXISTS pac_roles_caps_idx"

    drop table(:thunderpac_roles)

    drop table(:policy_evaluations)
  end
end
