defmodule Thunderline.Repo.Migrations.AddSpectralNormToModelTrials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:decision_traces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :feature_window_id, :uuid, null: false
      add :router_version, :text, null: false
      add :gate_scores, :map, null: false, default: %{}
      add :selected_experts, :map, null: false, default: %{}
      add :actions, :map, null: false, default: %{}
      add :blended_action, :map
      add :pnl_snapshot, :map
      add :risk_flags, :map, null: false, default: %{}
      add :behavior_embedding, :binary
      add :hash, :binary, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_rule_oracles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :implementation, :text, null: false
      add :description, :text
      add :input_size, :bigint, default: 16
      add :hidden_size, :bigint, default: 32
      add :batch_size, :bigint, default: 32
      add :temperature, :float, default: 1.0
      add :total_inferences, :bigint, default: 0
      add :avg_latency_us, :float
      add :error_rate, :float, default: 0.0
      add :last_inference_at, :utc_datetime
      add :model_version, :text
      add :training_examples, :bigint, default: 0
      add :model_size_bytes, :bigint
      add :rule_parameters, :map, default: %{}
      add :performance_metrics, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "initializing"
    end

    create table(:thundermag_task_executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :execution_id, :uuid, null: false
      add :macro_command_id, :uuid, null: false
      add :status, :text, null: false, default: "pending"
      add :total_tasks, :bigint, null: false, default: 0
      add :completed_tasks, :bigint, default: 0
      add :failed_tasks, :bigint, default: 0
      add :execution_plan, :map, default: %{}
      add :results, {:array, :map}, default: []
      add :errors, {:array, :map}, default: []
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :session_id, :uuid
      add :zone_assignments, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ml_consent_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :tenant_id, :text, null: false
      add :purpose, :text, null: false
      add :granted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ml_consent_records, [:user_id, :tenant_id, :purpose],
             name: "ml_consent_records_unique_consent_index"
           )

    create table(:ml_training_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :run_id, :text, null: false
      add :tenant_id, :text, null: false
      add :dataset_id, :uuid, null: false
      add :spec_id, :uuid, null: false
      add :artifact_id, :uuid
      add :params, :map, default: %{}
      add :status, :text, default: "queued"
      add :error, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thundercore_agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :agent_name, :text, null: false
      add :agent_type, :text, null: false
      add :status, :text, default: "starting"
      add :capabilities, :map, default: %{}
      add :current_task, :text
      add :last_heartbeat, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thundercore_agents, [:agent_name],
             name: "thundercore_agents_unique_agent_name_index"
           )

    create table(:export_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :slice_spec, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :artifact_uri, :text
      add :error, :text
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ml_model_specs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :text, null: false
      add :base_model, :text, null: false
      add :task, :text, null: false
      add :adapter, :text, null: false
      add :framework, :text, null: false
      add :params, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ml_model_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :spec_id,
          references(:ml_model_specs,
            column: :id,
            name: "ml_model_artifacts_spec_id_fkey",
            type: :uuid
          ),
          null: false

      add :model_run_id, :uuid
      add :uri, :text, null: false
      add :checksum, :text, null: false
      add :bytes, :bigint, null: false
      add :status, :text, default: "created"
      add :promoted, :boolean, default: false
      add :semver, :text, default: "0.1.0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_coordinators, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lane_dimension, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :active_ruleset_id, :uuid
      add :active_ruleset_version, :bigint
      add :status, :text, null: false, default: "initializing"
      add :topology_shape, :map, null: false
      add :cells_managed, :bigint, default: 0
      add :updates_per_second, :float, default: 0.0
      add :last_sync_at, :utc_datetime_usec
      add :coordination_latency_ms, :float
      add :coordinator_pid, :text
      add :coordinator_node, :text
      add :last_heartbeat_at, :utc_datetime_usec
      add :coupling_enabled, :boolean, null: false, default: true
      add :coupling_buffers, :map, default: %{}
      add :coupling_backpressure, :map, default: %{}
      add :event_queue_size, :bigint, default: 0
      add :events_processed, :bigint, default: 0
      add :events_dropped, :bigint, default: 0
      add :target_ups, :float, null: false, default: 1.0e3
      add :max_coordination_latency_ms, :float, null: false, default: 5.0
      add :max_queue_size, :bigint, null: false, default: 10000
      add :error_count, :bigint, default: 0
      add :last_error, :text
      add :last_error_at, :utc_datetime_usec
      add :config, :map, default: %{}
      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ml_feature_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :feature_view_id, :text, null: false
      add :dataset_id, :uuid, null: false
      add :name, :text, null: false
      add :schema_json, :map, null: false
      add :materialization, :text, null: false
      add :version, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderblock_retention_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource, :text, null: false
      add :scope_type, :text, default: "global"
      add :scope_id, :uuid
      add :ttl_seconds, :bigint
      add :keep_versions, :bigint
      add :action, :text, default: "delete"
      add :grace_seconds, :bigint, default: 0
      add :metadata, :map, default: %{}
      add :notes, :text
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thunderblock_retention_policies, [:resource, :scope_type, :scope_id],
             name: "thunderblock_retention_policies_policy_scope_index"
           )

    create table(:thundermag_macro_commands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thundermag_task_executions) do
      modify :macro_command_id,
             references(:thundermag_macro_commands,
               column: :id,
               name: "thundermag_task_executions_macro_command_id_fkey",
               type: :uuid
             )
    end

    alter table(:thundermag_macro_commands) do
      add :command_type, :text, null: false
      add :macro_input, :text, null: false
      add :micro_tasks, {:array, :map}, null: false, default: []
      add :status, :text, null: false, default: "pending"
      add :execution_metadata, :map, default: %{}
      add :session_id, :uuid
      add :zone_preferences, {:array, :text}, default: []
      add :priority, :text, default: "normal"
      add :estimated_duration_ms, :bigint
      add :actual_duration_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_rulesets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderlane_coordinators) do
      modify :active_ruleset_id,
             references(:thunderlane_rulesets,
               column: :id,
               name: "thunderlane_coordinators_active_ruleset_id_fkey",
               type: :uuid
             )
    end

    alter table(:thunderlane_rulesets) do
      add :version, :bigint, null: false
      add :name, :text, null: false
      add :description, :text
      add :x_lane_rule, :text, null: false
      add :y_lane_rule, :text, null: false
      add :z_lane_rule, :text, null: false
      add :x_lane_params, :map, default: %{}
      add :y_lane_params, :map, default: %{}
      add :z_lane_params, :map, default: %{}
      add :alpha_xy, :float, null: false, default: 0.35
      add :alpha_xz, :float, null: false, default: 0.15
      add :alpha_yx, :float, null: false, default: 0.35
      add :alpha_yz, :float, null: false, default: 0.2
      add :alpha_zx, :float, null: false, default: 0.15
      add :alpha_zy, :float, null: false, default: 0.25
      add :schedule_type, :text, null: false, default: "hybrid_event_wave"
      add :schedule_params, :map, default: %{}
      add :boundaries, :map
      add :parameter_bounds, :map, default: %{}
      add :objective_function, :map
      add :status, :text, null: false, default: "draft"
      add :deployed_at, :utc_datetime_usec
      add :performance_score, :float
      add :signature, :text
      add :signature_algorithm, :text, default: "ed25519"
      add :signed_by, :text
      add :metadata, :map, default: %{}
      add :lane_configuration_id, :uuid

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thundermag_task_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :task_execution_id,
          references(:thundermag_task_executions,
            column: :id,
            name: "thundermag_task_assignments_task_execution_id_fkey",
            type: :uuid
          ),
          null: false

      add :task_id, :uuid, null: false
      add :thunderbit_id, :uuid
      add :zone_id, :text
      add :task_type, :text, null: false
      add :task_value, :text
      add :sequence, :bigint
      add :status, :text, null: false, default: "assigned"
      add :priority, :text, default: "normal"
      add :estimated_execution_time_ms, :bigint
      add :actual_execution_time_ms, :bigint
      add :retry_count, :bigint, default: 0
      add :max_retries, :bigint, default: 3
      add :result, :map
      add :error, :map
      add :assigned_at, :utc_datetime
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_cross_lane_coupling, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_lane, :text, null: false
      add :target_lane, :text, null: false
      add :name, :text
      add :rule_set_id, :uuid
      add :alpha_gain, :float, null: false, default: 0.25
      add :coupling_type, :text, null: false, default: "symmetric"
      add :coupling_function, :text, null: false, default: "linear"
      add :coupling_params, :map, default: %{}
      add :spatial_kernel, :text, null: false, default: "cross_3x3"
      add :kernel_params, :map, default: %{}
      add :temporal_delay, :bigint, null: false, default: 0
      add :temporal_window, :bigint, null: false, default: 1
      add :adaptive_enabled, :boolean, null: false, default: false
      add :adaptation_rate, :float, default: 0.01
      add :adaptation_bounds, :map
      add :coupling_strength, :float
      add :mutual_information, :float
      add :phase_coherence, :float
      add :energy_transfer, :float
      add :stability_measure, :float
      add :status, :text, null: false, default: "inactive"
      add :buffer_size, :bigint, default: 0
      add :events_coupled, :bigint, default: 0
      add :coupling_latency_ms, :float
      add :error_count, :bigint, default: 0
      add :last_error, :text
      add :last_error_at, :utc_datetime_usec
      add :health_score, :float, default: 1.0
      add :tuning_history, :map, default: %{}
      add :performance_trend, :text
      add :config, :map, default: %{}
      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ruleset_id,
          references(:thunderlane_rulesets,
            column: :id,
            name: "thunderlane_cross_lane_coupling_ruleset_id_fkey",
            type: :uuid
          )
    end

    create unique_index(
             :thunderlane_cross_lane_coupling,
             [:source_lane, :target_lane, :ruleset_id],
             name: "thunderlane_cross_lane_coupling_unique_lane_coupling_index"
           )

    create table(:ising_optimization_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :problem_id, :uuid, null: false
      add :name, :text
      add :algorithm, :text, null: false
      add :parameters, :map, null: false
      add :status, :text, default: "queued"
      add :result, :map
      add :energy_history, {:array, :float}, default: []
      add :magnetization_history, {:array, :float}, default: []
      add :final_energy, :float
      add :final_magnetization, :float
      add :steps_completed, :bigint, default: 0
      add :runtime_ms, :bigint
      add :converged, :boolean, default: false
      add :error_message, :text
      add :metrics, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
    end

    create table(:lane_configurations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :lane_type, :text, null: false, default: "ca"
      add :lane_family, :text, null: false
      add :rule_parameters, :map, default: %{}
      add :performance_target, :decimal, default: "0.85"
      add :max_concurrent_tasks, :bigint, default: 10
      add :priority_weight, :decimal, default: "1.0"
      add :adaptive_bounds, :map
      add :metadata, :map, default: %{}

      add :rule_oracle_id,
          references(:thunderlane_rule_oracles,
            column: :id,
            name: "lane_configurations_rule_oracle_id_fkey",
            type: :uuid
          )

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "initializing"
    end

    create table(:thundercore_system_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :policy_name, :text, null: false
      add :policy_type, :text, null: false
      add :rule_definition, :map, null: false
      add :enforcement_level, :text, default: "warning"
      add :is_active, :boolean, default: true
      add :violation_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thundercore_system_policies, [:policy_name],
             name: "thundercore_system_policies_unique_policy_name_index"
           )

    create table(:cerebros_model_trials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :trial_id, :text, null: false
      add :status, :text, null: false, default: "succeeded"
      add :metrics, :map, default: %{}
      add :parameters, :map, default: %{}
      add :spectral_norm, :boolean, null: false, default: false
      add :mlflow_run_id, :text
      add :artifact_uri, :text
      add :duration_ms, :bigint
      add :rank, :bigint
      add :warnings, {:array, :text}, default: []
      add :candidate_id, :text
      add :pulse_id, :text
      add :bridge_payload, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :model_run_id, :uuid, null: false
    end

    create table(:ising_performance_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :benchmark_name, :text, null: false
      add :system_info, :map, null: false
      add :problem_size, :map, null: false
      add :algorithm_config, :map, null: false
      add :spins_per_second, :float
      add :energy_evaluations_per_second, :float
      add :memory_usage_mb, :float
      add :compilation_time_ms, :bigint
      add :execution_time_ms, :bigint
      add :total_time_ms, :bigint
      add :backend_info, :map, default: %{}
      add :scaling_factor, :float
      add :quality_metrics, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :environment_tags, {:array, :text}, default: []
    end

    create table(:thunderlane_lane_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :metric_type, :text, null: false
      add :source_type, :text, null: false
      add :source_id, :uuid
      add :lane_coordinator_id, :uuid
      add :cross_lane_coupling_id, :uuid
      add :rule_set_id, :uuid
      add :cell_topology_id, :uuid
      add :timestamp, :utc_datetime_usec, null: false
      add :measurement_window_ms, :bigint
      add :sequence_number, :bigint
      add :lane_dimension, :text
      add :updates_per_second, :float
      add :coordination_latency_ms, :float
      add :cells_processed, :bigint
      add :events_processed, :bigint
      add :queue_depth, :bigint
      add :coupling_strength, :float
      add :coupling_latency_ms, :float
      add :mutual_information, :float
      add :phase_coherence, :float
      add :energy_transfer, :float
      add :alpha_effectiveness, :float
      add :throughput, :float
      add :latency_p50_ms, :float
      add :latency_p95_ms, :float
      add :latency_p99_ms, :float
      add :error_rate, :float
      add :success_rate, :float
      add :cpu_usage_percent, :float
      add :memory_usage_mb, :float
      add :memory_usage_percent, :float
      add :network_io_mbps, :float
      add :disk_io_mbps, :float
      add :stability_score, :float, default: 1.0
      add :health_score, :float, default: 1.0
      add :anomaly_score, :float, default: 0.0
      add :optimization_target, :text
      add :optimization_score, :float
      add :improvement_factor, :float
      add :convergence_rate, :float
      add :pathflow_accuracy, :float
      add :pattern_recognition_rate, :float
      add :emergence_detection_count, :bigint
      add :computation_efficiency, :float
      add :raw_metrics, :map, default: %{}
      add :aggregated_metrics, :map, default: %{}
      add :trend_indicators, :map, default: %{}
      add :tags, :map, default: %{}
      add :metadata, :map, default: %{}
      add :measurement_confidence, :float, default: 1.0
      add :data_quality_score, :float, default: 1.0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :coordinator_id,
          references(:thunderlane_coordinators,
            column: :id,
            name: "thunderlane_lane_metrics_coordinator_id_fkey",
            type: :uuid
          )

      add :coupling_id,
          references(:thunderlane_cross_lane_coupling,
            column: :id,
            name: "thunderlane_lane_metrics_coupling_id_fkey",
            type: :uuid
          )

      add :topology_id, :uuid
      add :ruleset_id, :uuid
    end

    create table(:experts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :name, :text, null: false
      add :version, :text, null: false
      add :status, :text, null: false, default: "active"
      add :latency_budget_ms, :bigint
      add :metrics, :map, null: false, default: %{}
      add :model_artifact_ref, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thundercore_task_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_name, :text, null: false
      add :task_type, :text, null: false
      add :task_config, :map, default: %{}
      add :status, :text, default: "pending"
      add :dependencies, {:array, :text}, default: []
      add :position_x, :bigint, default: 0
      add :position_y, :bigint, default: 0
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workflow_dag_id, :uuid
    end

    create table(:thunderlane_performance_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :coordinator_id, :text
      add :metric_type, :text, null: false
      add :step_number, :bigint, null: false
      add :micro_latency_us, :bigint
      add :meso_latency_us, :bigint
      add :macro_latency_us, :bigint
      add :total_latency_us, :bigint
      add :patches_processed, :bigint, default: 0
      add :consensus_bursts, :bigint, default: 0
      add :fusion_operations, :bigint, default: 0
      add :system_energy, :float
      add :energy_drift, :float
      add :stability_score, :float
      add :convergence_rate, :float
      add :lane_x_energy, :float
      add :lane_y_energy, :float
      add :lane_z_energy, :float
      add :alpha_xy, :float
      add :alpha_xz, :float
      add :alpha_yz, :float
      add :oracle_batch_size, :bigint
      add :oracle_success_rate, :float
      add :oracle_latency_us, :bigint
      add :cpu_usage_percent, :float
      add :memory_usage_mb, :bigint
      add :gpu_usage_percent, :float

      add :lane_configuration_id,
          references(:lane_configurations,
            column: :id,
            name: "thunderlane_performance_metrics_lane_configuration_id_fkey",
            type: :uuid
          )

      add :rule_oracle_id,
          references(:thunderlane_rule_oracles,
            column: :id,
            name: "thunderlane_performance_metrics_rule_oracle_id_fkey",
            type: :uuid
          )

      add :telemetry_snapshot_id, :uuid
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_consensus_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :region_id, :text
      add :trigger_reason, :text
      add :matrix_size, :bigint, null: false
      add :coupling_strength, :float, default: 1.0
      add :initial_temperature, :float, default: 1.5
      add :final_temperature, :float, default: 0.1
      add :max_steps, :bigint, default: 50
      add :final_energy, :float
      add :convergence_steps, :bigint
      add :success, :boolean, default: false
      add :execution_time_ms, :bigint
      add :spin_configuration, :map, default: %{}

      add :lane_configuration_id,
          references(:lane_configurations,
            column: :id,
            name: "thunderlane_consensus_runs_lane_configuration_id_fkey",
            type: :uuid
          )

      add :rule_oracle_id,
          references(:thunderlane_rule_oracles,
            column: :id,
            name: "thunderlane_consensus_runs_rule_oracle_id_fkey",
            type: :uuid
          )

      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ml_model_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_id, :text, null: false

      add :spec_id,
          references(:ml_model_specs,
            column: :id,
            name: "ml_model_versions_spec_id_fkey",
            type: :uuid
          ),
          null: false

      add :artifact_id,
          references(:ml_model_artifacts,
            column: :id,
            name: "ml_model_versions_artifact_id_fkey",
            type: :uuid
          ),
          null: false

      add :dataset_id, :uuid, null: false
      add :metrics, :map, default: %{}
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_telemetry_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderlane_performance_metrics) do
      modify :telemetry_snapshot_id,
             references(:thunderlane_telemetry_snapshots,
               column: :id,
               name: "thunderlane_performance_metrics_telemetry_snapshot_id_fkey",
               type: :uuid
             )
    end

    alter table(:thunderlane_telemetry_snapshots) do
      add :coordinator_id, :text, null: false
      add :snapshot_type, :text, null: false
      add :window_start_ms, :bigint
      add :window_end_ms, :bigint
      add :window_duration_ms, :bigint
      add :total_events, :bigint, default: 0
      add :event_rate_per_second, :float
      add :burst_count, :bigint, default: 0
      add :anti_bunching_effectiveness, :float
      add :displacement_mean, :float
      add :displacement_variance, :float
      add :tail_exponent, :float
      add :tail_fit_quality, :float
      add :latency_mean_us, :float
      add :latency_median_us, :float
      add :latency_p90_us, :bigint
      add :latency_p95_us, :bigint
      add :latency_p99_us, :bigint
      add :latency_p999_us, :bigint
      add :latency_max_us, :bigint
      add :queue_depth_mean, :float
      add :queue_depth_max, :bigint
      add :backpressure_events, :bigint, default: 0
      add :dropped_events, :bigint, default: 0
      add :cpu_usage_mean, :float
      add :memory_usage_mean_mb, :bigint
      add :memory_usage_max_mb, :bigint
      add :gc_count, :bigint, default: 0
      add :gc_total_time_ms, :bigint, default: 0
      add :network_bytes_in, :bigint, default: 0
      add :network_bytes_out, :bigint, default: 0
      add :coordination_messages, :bigint, default: 0
      add :coordination_latency_us, :bigint
      add :error_count, :bigint, default: 0
      add :anomaly_score, :float, default: 0.0
      add :anomaly_features, :map, default: %{}

      add :lane_configuration_id,
          references(:lane_configurations,
            column: :id,
            name: "thunderlane_telemetry_snapshots_lane_configuration_id_fkey",
            type: :uuid
          )

      add :rule_oracle_id,
          references(:thunderlane_rule_oracles,
            column: :id,
            name: "thunderlane_telemetry_snapshots_rule_oracle_id_fkey",
            type: :uuid
          )

      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlane_cell_topology, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderlane_lane_metrics) do
      modify :topology_id,
             references(:thunderlane_cell_topology,
               column: :id,
               name: "thunderlane_lane_metrics_topology_id_fkey",
               type: :uuid
             )

      modify :ruleset_id,
             references(:thunderlane_rulesets,
               column: :id,
               name: "thunderlane_lane_metrics_ruleset_id_fkey",
               type: :uuid
             )
    end

    alter table(:thunderlane_cell_topology) do
      add :name, :text, null: false
      add :description, :text
      add :lane_coordinator_id, :uuid
      add :width, :bigint, null: false
      add :height, :bigint, null: false
      add :depth, :bigint, null: false
      add :total_cells, :bigint
      add :cells_per_partition, :bigint
      add :partition_count, :bigint
      add :topology_type, :text, null: false, default: "rectangular"
      add :boundary_x, :text, null: false, default: "wrap"
      add :boundary_y, :text, null: false, default: "wrap"
      add :boundary_z, :text, null: false, default: "wrap"
      add :neighborhood_type, :text, null: false, default: "moore_3d"
      add :neighborhood_radius, :bigint, null: false, default: 1
      add :partitioning_strategy, :text, null: false, default: "grid_3d"
      add :partitioning_config, :map, default: %{}
      add :thundercell_nodes, :map, default: %{}
      add :partition_assignments, :map, default: %{}
      add :node_load_balance, :map, default: %{}
      add :average_neighbors_per_cell, :float
      add :max_partition_size, :bigint
      add :min_partition_size, :bigint
      add :load_variance, :float
      add :status, :text, null: false, default: "designed"
      add :distribution_health, :float, default: 1.0
      add :last_rebalance_at, :utc_datetime_usec
      add :locality_score, :float
      add :communication_overhead, :float
      add :memory_efficiency, :float
      add :initial_state_pattern, :text
      add :initial_state_config, :map, default: %{}
      add :initial_state_seed, :bigint
      add :config, :map, default: %{}
      add :metadata, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :coordinator_id,
          references(:thunderlane_coordinators,
            column: :id,
            name: "thunderlane_cell_topology_coordinator_id_fkey",
            type: :uuid
          )
    end

    create table(:cerebros_model_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ml_model_artifacts) do
      modify :model_run_id,
             references(:cerebros_model_runs,
               column: :id,
               name: "ml_model_artifacts_model_run_id_fkey",
               type: :uuid
             )
    end

    alter table(:cerebros_model_trials) do
      modify :model_run_id,
             references(:cerebros_model_runs,
               column: :id,
               name: "cerebros_model_trials_model_run_id_fkey",
               type: :uuid
             )
    end

    alter table(:cerebros_model_runs) do
      add :run_id, :text, null: false
      add :state, :text, null: false, default: "initialized"
      add :search_space_version, :bigint, null: false, default: 1
      add :max_params, :bigint, null: false, default: 2_000_000
      add :requested_trials, :bigint, null: false, default: 3
      add :completed_trials, :bigint, default: 0
      add :best_metric, :float
      add :error_message, :text
      add :metadata, :map, default: %{}
      add :bridge_payload, :map, default: %{}
      add :bridge_result, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ising_optimization_problems, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ising_optimization_runs) do
      modify :problem_id,
             references(:ising_optimization_problems,
               column: :id,
               name: "ising_optimization_runs_problem_id_fkey",
               type: :uuid
             )
    end

    alter table(:ising_optimization_problems) do
      add :name, :text, null: false
      add :description, :text
      add :topology, :text, null: false
      add :dimensions, :map, null: false
      add :coupling_matrix, :map
      add :field_config, :map
      add :boundary_conditions, :text, default: "periodic"
      add :problem_type, :text, null: false
      add :edge_list, {:array, :map}
      add :metadata, :map, default: %{}
      add :tags, {:array, :text}, default: []

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thundercore_workflow_dags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thundercore_task_nodes) do
      modify :workflow_dag_id,
             references(:thundercore_workflow_dags,
               column: :id,
               name: "thundercore_task_nodes_workflow_dag_id_fkey",
               type: :uuid
             )
    end

    alter table(:thundercore_workflow_dags) do
      add :name, :text, null: false
      add :description, :text
      add :status, :text, default: "pending"
      add :priority, :bigint, default: 5
      add :metadata, :map, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thundercore_workflow_dags, [:name],
             name: "thundercore_workflow_dags_unique_workflow_name_index"
           )

    create table(:thundercore_timing_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_name, :text, null: false
      add :event_type, :text, null: false
      add :scheduled_at, :utc_datetime_usec, null: false
      add :executed_at, :utc_datetime_usec
      add :status, :text, default: "scheduled"
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:users) do
      modify :password, :text, null: true
    end

    create table(:ml_training_datasets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ml_training_runs) do
      modify :dataset_id,
             references(:ml_training_datasets,
               column: :id,
               name: "ml_training_runs_dataset_id_fkey",
               type: :uuid
             )

      modify :spec_id,
             references(:ml_model_specs,
               column: :id,
               name: "ml_training_runs_spec_id_fkey",
               type: :uuid
             )

      modify :artifact_id,
             references(:ml_model_artifacts,
               column: :id,
               name: "ml_training_runs_artifact_id_fkey",
               type: :uuid
             )
    end

    alter table(:ml_feature_views) do
      modify :dataset_id,
             references(:ml_training_datasets,
               column: :id,
               name: "ml_feature_views_dataset_id_fkey",
               type: :uuid
             )
    end

    alter table(:ml_model_versions) do
      modify :dataset_id,
             references(:ml_training_datasets,
               column: :id,
               name: "ml_model_versions_dataset_id_fkey",
               type: :uuid
             )
    end

    alter table(:ml_training_datasets) do
      add :dataset_id, :text, null: false
      add :tenant_id, :text, null: false
      add :name, :text, null: false
      add :purpose, :text, null: false
      add :description, :text
      add :version, :bigint, default: 1
      add :status, :text, default: "draft"
      add :bytes, :bigint
      add :records, :bigint
      add :checksum, :text
      add :sealed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:ml_training_datasets) do
      remove :updated_at
      remove :inserted_at
      remove :sealed_at
      remove :checksum
      remove :records
      remove :bytes
      remove :status
      remove :version
      remove :description
      remove :purpose
      remove :name
      remove :tenant_id
      remove :dataset_id
    end

    drop constraint(:ml_model_versions, "ml_model_versions_dataset_id_fkey")

    alter table(:ml_model_versions) do
      modify :dataset_id, :uuid
    end

    drop constraint(:ml_feature_views, "ml_feature_views_dataset_id_fkey")

    alter table(:ml_feature_views) do
      modify :dataset_id, :uuid
    end

    drop constraint(:ml_training_runs, "ml_training_runs_dataset_id_fkey")

    drop constraint(:ml_training_runs, "ml_training_runs_spec_id_fkey")

    drop constraint(:ml_training_runs, "ml_training_runs_artifact_id_fkey")

    alter table(:ml_training_runs) do
      modify :artifact_id, :uuid
      modify :spec_id, :uuid
      modify :dataset_id, :uuid
    end

    drop table(:ml_training_datasets)

    alter table(:users) do
      modify :password, :text, null: false
    end

    drop table(:thundercore_timing_events)

    drop_if_exists unique_index(:thundercore_workflow_dags, [:name],
                     name: "thundercore_workflow_dags_unique_workflow_name_index"
                   )

    alter table(:thundercore_workflow_dags) do
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :metadata
      remove :priority
      remove :status
      remove :description
      remove :name
    end

    drop constraint(:thundercore_task_nodes, "thundercore_task_nodes_workflow_dag_id_fkey")

    alter table(:thundercore_task_nodes) do
      modify :workflow_dag_id, :uuid
    end

    drop table(:thundercore_workflow_dags)

    alter table(:ising_optimization_problems) do
      remove :updated_at
      remove :created_at
      remove :tags
      remove :metadata
      remove :edge_list
      remove :problem_type
      remove :boundary_conditions
      remove :field_config
      remove :coupling_matrix
      remove :dimensions
      remove :topology
      remove :description
      remove :name
    end

    drop constraint(:ising_optimization_runs, "ising_optimization_runs_problem_id_fkey")

    alter table(:ising_optimization_runs) do
      modify :problem_id, :uuid
    end

    drop table(:ising_optimization_problems)

    alter table(:cerebros_model_runs) do
      remove :updated_at
      remove :inserted_at
      remove :finished_at
      remove :started_at
      remove :bridge_result
      remove :bridge_payload
      remove :metadata
      remove :error_message
      remove :best_metric
      remove :completed_trials
      remove :requested_trials
      remove :max_params
      remove :search_space_version
      remove :state
      remove :run_id
    end

    drop constraint(:cerebros_model_trials, "cerebros_model_trials_model_run_id_fkey")

    alter table(:cerebros_model_trials) do
      modify :model_run_id, :uuid
    end

    drop constraint(:ml_model_artifacts, "ml_model_artifacts_model_run_id_fkey")

    alter table(:ml_model_artifacts) do
      modify :model_run_id, :uuid
    end

    drop table(:cerebros_model_runs)

    drop constraint(:thunderlane_cell_topology, "thunderlane_cell_topology_coordinator_id_fkey")

    alter table(:thunderlane_cell_topology) do
      remove :coordinator_id
      remove :updated_at
      remove :created_at
      remove :metadata
      remove :config
      remove :initial_state_seed
      remove :initial_state_config
      remove :initial_state_pattern
      remove :memory_efficiency
      remove :communication_overhead
      remove :locality_score
      remove :last_rebalance_at
      remove :distribution_health
      remove :status
      remove :load_variance
      remove :min_partition_size
      remove :max_partition_size
      remove :average_neighbors_per_cell
      remove :node_load_balance
      remove :partition_assignments
      remove :thundercell_nodes
      remove :partitioning_config
      remove :partitioning_strategy
      remove :neighborhood_radius
      remove :neighborhood_type
      remove :boundary_z
      remove :boundary_y
      remove :boundary_x
      remove :topology_type
      remove :partition_count
      remove :cells_per_partition
      remove :total_cells
      remove :depth
      remove :height
      remove :width
      remove :lane_coordinator_id
      remove :description
      remove :name
    end

    drop constraint(:thunderlane_lane_metrics, "thunderlane_lane_metrics_topology_id_fkey")

    drop constraint(:thunderlane_lane_metrics, "thunderlane_lane_metrics_ruleset_id_fkey")

    alter table(:thunderlane_lane_metrics) do
      modify :ruleset_id, :uuid
      modify :topology_id, :uuid
    end

    drop table(:thunderlane_cell_topology)

    drop constraint(
           :thunderlane_telemetry_snapshots,
           "thunderlane_telemetry_snapshots_lane_configuration_id_fkey"
         )

    drop constraint(
           :thunderlane_telemetry_snapshots,
           "thunderlane_telemetry_snapshots_rule_oracle_id_fkey"
         )

    alter table(:thunderlane_telemetry_snapshots) do
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :rule_oracle_id
      remove :lane_configuration_id
      remove :anomaly_features
      remove :anomaly_score
      remove :error_count
      remove :coordination_latency_us
      remove :coordination_messages
      remove :network_bytes_out
      remove :network_bytes_in
      remove :gc_total_time_ms
      remove :gc_count
      remove :memory_usage_max_mb
      remove :memory_usage_mean_mb
      remove :cpu_usage_mean
      remove :dropped_events
      remove :backpressure_events
      remove :queue_depth_max
      remove :queue_depth_mean
      remove :latency_max_us
      remove :latency_p999_us
      remove :latency_p99_us
      remove :latency_p95_us
      remove :latency_p90_us
      remove :latency_median_us
      remove :latency_mean_us
      remove :tail_fit_quality
      remove :tail_exponent
      remove :displacement_variance
      remove :displacement_mean
      remove :anti_bunching_effectiveness
      remove :burst_count
      remove :event_rate_per_second
      remove :total_events
      remove :window_duration_ms
      remove :window_end_ms
      remove :window_start_ms
      remove :snapshot_type
      remove :coordinator_id
    end

    drop constraint(
           :thunderlane_performance_metrics,
           "thunderlane_performance_metrics_telemetry_snapshot_id_fkey"
         )

    alter table(:thunderlane_performance_metrics) do
      modify :telemetry_snapshot_id, :uuid
    end

    drop table(:thunderlane_telemetry_snapshots)

    drop constraint(:ml_model_versions, "ml_model_versions_spec_id_fkey")

    drop constraint(:ml_model_versions, "ml_model_versions_artifact_id_fkey")

    drop table(:ml_model_versions)

    drop constraint(
           :thunderlane_consensus_runs,
           "thunderlane_consensus_runs_lane_configuration_id_fkey"
         )

    drop constraint(:thunderlane_consensus_runs, "thunderlane_consensus_runs_rule_oracle_id_fkey")

    drop table(:thunderlane_consensus_runs)

    drop constraint(
           :thunderlane_performance_metrics,
           "thunderlane_performance_metrics_lane_configuration_id_fkey"
         )

    drop constraint(
           :thunderlane_performance_metrics,
           "thunderlane_performance_metrics_rule_oracle_id_fkey"
         )

    drop table(:thunderlane_performance_metrics)

    drop table(:thundercore_task_nodes)

    drop table(:experts)

    drop constraint(:thunderlane_lane_metrics, "thunderlane_lane_metrics_coordinator_id_fkey")

    drop constraint(:thunderlane_lane_metrics, "thunderlane_lane_metrics_coupling_id_fkey")

    drop table(:thunderlane_lane_metrics)

    drop table(:ising_performance_metrics)

    drop table(:cerebros_model_trials)

    drop_if_exists unique_index(:thundercore_system_policies, [:policy_name],
                     name: "thundercore_system_policies_unique_policy_name_index"
                   )

    drop table(:thundercore_system_policies)

    drop constraint(:lane_configurations, "lane_configurations_rule_oracle_id_fkey")

    drop table(:lane_configurations)

    drop table(:ising_optimization_runs)

    drop_if_exists unique_index(
                     :thunderlane_cross_lane_coupling,
                     [:source_lane, :target_lane, :ruleset_id],
                     name: "thunderlane_cross_lane_coupling_unique_lane_coupling_index"
                   )

    drop constraint(
           :thunderlane_cross_lane_coupling,
           "thunderlane_cross_lane_coupling_ruleset_id_fkey"
         )

    drop table(:thunderlane_cross_lane_coupling)

    drop constraint(
           :thundermag_task_assignments,
           "thundermag_task_assignments_task_execution_id_fkey"
         )

    drop table(:thundermag_task_assignments)

    alter table(:thunderlane_rulesets) do
      remove :updated_at
      remove :created_at
      remove :lane_configuration_id
      remove :metadata
      remove :signed_by
      remove :signature_algorithm
      remove :signature
      remove :performance_score
      remove :deployed_at
      remove :status
      remove :objective_function
      remove :parameter_bounds
      remove :boundaries
      remove :schedule_params
      remove :schedule_type
      remove :alpha_zy
      remove :alpha_zx
      remove :alpha_yz
      remove :alpha_yx
      remove :alpha_xz
      remove :alpha_xy
      remove :z_lane_params
      remove :y_lane_params
      remove :x_lane_params
      remove :z_lane_rule
      remove :y_lane_rule
      remove :x_lane_rule
      remove :description
      remove :name
      remove :version
    end

    drop constraint(:thunderlane_coordinators, "thunderlane_coordinators_active_ruleset_id_fkey")

    alter table(:thunderlane_coordinators) do
      modify :active_ruleset_id, :uuid
    end

    drop table(:thunderlane_rulesets)

    alter table(:thundermag_macro_commands) do
      remove :updated_at
      remove :inserted_at
      remove :actual_duration_ms
      remove :estimated_duration_ms
      remove :priority
      remove :zone_preferences
      remove :session_id
      remove :execution_metadata
      remove :status
      remove :micro_tasks
      remove :macro_input
      remove :command_type
    end

    drop constraint(
           :thundermag_task_executions,
           "thundermag_task_executions_macro_command_id_fkey"
         )

    alter table(:thundermag_task_executions) do
      modify :macro_command_id, :uuid
    end

    drop table(:thundermag_macro_commands)

    drop_if_exists unique_index(
                     :thunderblock_retention_policies,
                     [:resource, :scope_type, :scope_id],
                     name: "thunderblock_retention_policies_policy_scope_index"
                   )

    drop table(:thunderblock_retention_policies)

    drop table(:ml_feature_views)

    drop table(:thunderlane_coordinators)

    drop constraint(:ml_model_artifacts, "ml_model_artifacts_spec_id_fkey")

    drop table(:ml_model_artifacts)

    drop table(:ml_model_specs)

    drop table(:export_jobs)

    drop_if_exists unique_index(:thundercore_agents, [:agent_name],
                     name: "thundercore_agents_unique_agent_name_index"
                   )

    drop table(:thundercore_agents)

    drop table(:ml_training_runs)

    drop_if_exists unique_index(:ml_consent_records, [:user_id, :tenant_id, :purpose],
                     name: "ml_consent_records_unique_consent_index"
                   )

    drop table(:ml_consent_records)

    drop table(:thundermag_task_executions)

    drop table(:thunderlane_rule_oracles)

    drop table(:decision_traces)
  end
end
