defmodule Thunderline.Repo.Migrations.AddUpmObservations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:upm_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :pac_id, :uuid
      add :domain, :text, null: false
      add :tick, :bigint, null: false, default: 0
      add :plv, :float
      add :sigma, :float
      add :lambda, :float
      add :rtau, :float
      add :entropy, :float
      add :band_status, :text, null: false, default: "unknown"
      add :intervention_triggered, :boolean, default: false
      add :intervention_type, :text
      add :activations_shape, :map, default: %{}
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :snapshot_id,
          references(:upm_snapshots,
            column: :id,
            name: "upm_observations_snapshot_id_fkey",
            type: :uuid
          )
    end

    create index(:upm_observations, [:inserted_at], name: "upm_observations_inserted_at_idx")

    create index(:upm_observations, [:band_status], name: "upm_observations_band_status_idx")

    create index(:upm_observations, [:pac_id, :domain, :tick],
             name: "upm_observations_pac_domain_tick_idx"
           )

    create unique_index(:upm_observations, [:pac_id, :domain, :tick],
             name: "upm_observations_unique_observation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:upm_observations, [:pac_id, :domain, :tick],
                     name: "upm_observations_unique_observation_index"
                   )

    drop constraint(:upm_observations, "upm_observations_snapshot_id_fkey")

    drop_if_exists index(:upm_observations, [:pac_id, :domain, :tick],
                     name: "upm_observations_pac_domain_tick_idx"
                   )

    drop_if_exists index(:upm_observations, [:band_status],
                     name: "upm_observations_band_status_idx"
                   )

    drop_if_exists index(:upm_observations, [:inserted_at],
                     name: "upm_observations_inserted_at_idx"
                   )

    drop table(:upm_observations)
  end
end
