defmodule Thunderline.Repo.Migrations.AddAiChat do
  @moduledoc """
  Introduce AI chat tables (conversations & messages).

  NOTE: Original autogenerated migration also attempted to (re)create DAG related tables
  which already exist in prior migrations. It was trimmed to avoid duplicate_table errors.
  """

  use Ecto.Migration

  def up do
    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "messages_conversation_id_fkey",
            type: :uuid
          ),
          null: false

      add :response_to_id,
          references(:messages, column: :id, name: "messages_response_to_id_fkey", type: :uuid)
    end

    create index(:messages, [:conversation_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:messages, [:conversation_id, :inserted_at])
    drop_if_exists constraint(:messages, "messages_conversation_id_fkey")
    drop_if_exists constraint(:messages, "messages_response_to_id_fkey")
    drop_if_exists table(:messages)
    drop_if_exists table(:conversations)
  end
end
