defmodule Thunderline.Repo.Migrations.AddTenantIdColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # TEMPORARILY COMMENTED OUT - embedding_vectors table not created yet
    # drop constraint(:embedding_vectors, "embedding_vectors_knowledge_node_id_fkey")

    # alter table(:embedding_vectors) do
    #   modify :knowledge_node_id,
    #          references(:thunderblock_knowledge_nodes,
    #            column: :id,
    #            name: "embedding_vectors_knowledge_node_id_fkey",
    #            type: :uuid
    #          )
    # end

    drop_if_exists index(:thunderblock_knowledge_nodes, [:embedding_vector_ids],
                     name: "knowledge_nodes_embeddings_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:memory_record_ids],
                     name: "knowledge_nodes_memories_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:taxonomy_path],
                     name: "knowledge_nodes_taxonomy_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:relationship_data],
                     name: "knowledge_nodes_relationships_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:source_domains],
                     name: "knowledge_nodes_sources_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:semantic_tags],
                     name: "knowledge_nodes_tags_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:aliases],
                     name: "knowledge_nodes_aliases_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:indexing_status],
                     name: "knowledge_nodes_indexing_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:confidence_level, :evidence_strength],
                     name: "knowledge_nodes_quality_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:verification_status, :centrality_score],
                     name: "knowledge_nodes_verification_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:node_type, :knowledge_domain],
                     name: "knowledge_nodes_type_domain_idx"
                   )

    alter table(:thunderblock_knowledge_nodes) do
      add :tenant_id, :uuid, null: false
    end

    create index(:thunderblock_knowledge_nodes, [:embedding_vector_ids],
             name: "knowledge_nodes_embeddings_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:memory_record_ids],
             name: "knowledge_nodes_memories_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:taxonomy_path],
             name: "knowledge_nodes_taxonomy_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:relationship_data],
             name: "knowledge_nodes_relationships_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:source_domains],
             name: "knowledge_nodes_sources_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:semantic_tags],
             name: "knowledge_nodes_tags_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:aliases],
             name: "knowledge_nodes_aliases_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:tenant_id, :indexing_status],
             name: "knowledge_nodes_indexing_idx"
           )

    create index(
             :thunderblock_knowledge_nodes,
             [:tenant_id, :confidence_level, :evidence_strength],
             name: "knowledge_nodes_quality_idx"
           )

    create index(
             :thunderblock_knowledge_nodes,
             [:tenant_id, :verification_status, :centrality_score],
             name: "knowledge_nodes_verification_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:tenant_id, :node_type, :knowledge_domain],
             name: "knowledge_nodes_type_domain_idx"
           )

    drop_if_exists unique_index(:thunderblock_knowledge_nodes, [:title, :knowledge_domain],
                     name: "thunderblock_knowledge_nodes_unique_title_domain_index"
                   )

    create unique_index(:thunderblock_knowledge_nodes, [:tenant_id, :title, :knowledge_domain],
             name: "thunderblock_knowledge_nodes_unique_title_domain_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :thunderblock_knowledge_nodes,
                     [:tenant_id, :title, :knowledge_domain],
                     name: "thunderblock_knowledge_nodes_unique_title_domain_index"
                   )

    create unique_index(:thunderblock_knowledge_nodes, [:title, :knowledge_domain],
             name: "thunderblock_knowledge_nodes_unique_title_domain_index"
           )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:tenant_id, :node_type, :knowledge_domain],
                     name: "knowledge_nodes_type_domain_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:tenant_id, :verification_status, :centrality_score],
                     name: "knowledge_nodes_verification_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:tenant_id, :confidence_level, :evidence_strength],
                     name: "knowledge_nodes_quality_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:tenant_id, :indexing_status],
                     name: "knowledge_nodes_indexing_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:aliases],
                     name: "knowledge_nodes_aliases_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:semantic_tags],
                     name: "knowledge_nodes_tags_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:source_domains],
                     name: "knowledge_nodes_sources_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:relationship_data],
                     name: "knowledge_nodes_relationships_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:taxonomy_path],
                     name: "knowledge_nodes_taxonomy_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:memory_record_ids],
                     name: "knowledge_nodes_memories_idx"
                   )

    drop_if_exists index(
                     :thunderblock_knowledge_nodes,
                     [:embedding_vector_ids],
                     name: "knowledge_nodes_embeddings_idx"
                   )

    alter table(:thunderblock_knowledge_nodes) do
      remove :tenant_id
    end

    create index(:thunderblock_knowledge_nodes, [:node_type, :knowledge_domain],
             name: "knowledge_nodes_type_domain_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:verification_status, :centrality_score],
             name: "knowledge_nodes_verification_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:confidence_level, :evidence_strength],
             name: "knowledge_nodes_quality_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:indexing_status],
             name: "knowledge_nodes_indexing_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:aliases],
             name: "knowledge_nodes_aliases_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:semantic_tags],
             name: "knowledge_nodes_tags_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:source_domains],
             name: "knowledge_nodes_sources_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:relationship_data],
             name: "knowledge_nodes_relationships_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:taxonomy_path],
             name: "knowledge_nodes_taxonomy_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:memory_record_ids],
             name: "knowledge_nodes_memories_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:embedding_vector_ids],
             name: "knowledge_nodes_embeddings_idx",
             using: :gin
           )

    # TEMPORARILY COMMENTED OUT - embedding_vectors table not created yet
    # drop constraint(:embedding_vectors, "embedding_vectors_knowledge_node_id_fkey")

    # alter table(:embedding_vectors) do
    #   modify :knowledge_node_id,
    #          references(:thunderblock_knowledge_nodes,
    #            column: :id,
    #            name: "embedding_vectors_knowledge_node_id_fkey",
    #            type: :uuid
    #          )
    # end
  end
end
