defmodule Thunderline.Repo.Migrations.AddMlflowTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mlflow_experiments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mlflow_experiment_id, :text, null: false
      add :name, :text, null: false
      add :artifact_location, :text
      add :lifecycle_stage, :text, default: "active"
      add :tags, :map, default: %{}

      add :model_run_id,
          references(:cerebros_model_runs,
            column: :id,
            name: "mlflow_experiments_model_run_id_fkey",
            type: :uuid
          )

      add :synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mlflow_experiments, [:mlflow_experiment_id],
             name: "mlflow_experiments_unique_mlflow_experiment_id_index"
           )

    create table(:mlflow_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mlflow_run_id, :text, null: false

      add :mlflow_experiment_id,
          references(:mlflow_experiments,
            column: :mlflow_experiment_id,
            name: "mlflow_runs_mlflow_experiment_id_fkey",
            type: :text
          ),
          null: false

      add :run_name, :text
      add :status, :text, default: "running"
      add :start_time, :bigint
      add :end_time, :bigint
      add :lifecycle_stage, :text, default: "active"
      add :artifact_uri, :text
      add :params, :map, default: %{}
      add :metrics, :map, default: %{}
      add :tags, :map, default: %{}

      add :model_trial_id,
          references(:cerebros_model_trials,
            column: :id,
            name: "mlflow_runs_model_trial_id_fkey",
            type: :uuid
          )

      add :model_run_id,
          references(:cerebros_model_runs,
            column: :id,
            name: "mlflow_runs_model_run_id_fkey",
            type: :uuid
          )

      add :synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mlflow_runs, [:mlflow_run_id],
             name: "mlflow_runs_unique_mlflow_run_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mlflow_runs, [:mlflow_run_id],
                     name: "mlflow_runs_unique_mlflow_run_id_index"
                   )

    drop constraint(:mlflow_runs, "mlflow_runs_mlflow_experiment_id_fkey")

    drop constraint(:mlflow_runs, "mlflow_runs_model_trial_id_fkey")

    drop constraint(:mlflow_runs, "mlflow_runs_model_run_id_fkey")

    drop table(:mlflow_runs)

    drop_if_exists unique_index(:mlflow_experiments, [:mlflow_experiment_id],
                     name: "mlflow_experiments_unique_mlflow_experiment_id_index"
                   )

    drop constraint(:mlflow_experiments, "mlflow_experiments_model_run_id_fkey")

    drop table(:mlflow_experiments)
  end
end
