defmodule Thunderline.Repo.Migrations.AddIntrinsicRewardToProbeRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:probe_runs) do
      add :intrinsic_reward, :decimal
    end

    # Only modify embedding_vectors if it exists
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'embedding_vectors') THEN
        ALTER TABLE embedding_vectors DROP CONSTRAINT IF EXISTS embedding_vectors_knowledge_node_id_fkey;
        ALTER TABLE embedding_vectors ALTER COLUMN knowledge_node_id TYPE uuid USING knowledge_node_id::uuid;
        ALTER TABLE embedding_vectors ADD CONSTRAINT embedding_vectors_knowledge_node_id_fkey
          FOREIGN KEY (knowledge_node_id) REFERENCES thunderblock_knowledge_nodes(id);
      END IF;
    END $$;
    """)
  end

  def down do
    # Only modify embedding_vectors if it exists
    execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'embedding_vectors') THEN
        ALTER TABLE embedding_vectors DROP CONSTRAINT IF EXISTS embedding_vectors_knowledge_node_id_fkey;
        ALTER TABLE embedding_vectors ALTER COLUMN knowledge_node_id TYPE uuid USING knowledge_node_id::uuid;
        ALTER TABLE embedding_vectors ADD CONSTRAINT embedding_vectors_knowledge_node_id_fkey
          FOREIGN KEY (knowledge_node_id) REFERENCES thunderblock_knowledge_nodes(id);
      END IF;
    END $$;
    """)

    alter table(:probe_runs) do
      remove :intrinsic_reward
    end
  end
end
