defmodule Thunderline.Repo.Migrations.AddActiveDomainRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:active_domain_registry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain_name, :text, null: false
      add :status, :text, null: false, default: "active"
      add :tick_count, :bigint, null: false
      add :metadata, :map, default: %{}

      add :activated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:active_domain_registry, [:domain_name],
             name: "active_domain_registry_unique_domain_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:active_domain_registry, [:domain_name],
                     name: "active_domain_registry_unique_domain_name_index"
                   )

    drop table(:active_domain_registry)
  end
end
