defmodule Thunderline.Repo.Migrations.CreateBaseTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:thunderblock_knowledge_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_type, :text, null: false, default: "concept"
      add :title, :text, null: false
      add :description, :text
      add :aliases, {:array, :text}, null: false, default: []
      add :knowledge_domain, :text, null: false
      add :source_domains, {:array, :text}, null: false, default: []
      add :confidence_level, :decimal, null: false, default: "1.0"
      add :evidence_strength, :decimal, null: false, default: "1.0"
      add :centrality_score, :decimal, null: false, default: "0.5"
      add :memory_record_ids, {:array, :uuid}, null: false, default: []
      add :embedding_vector_ids, {:array, :uuid}, null: false, default: []
      add :relationship_data, :map, null: false
      add :semantic_tags, {:array, :text}, null: false, default: []
      add :temporal_data, :map, null: false
      add :spatial_data, :map, null: false
      add :graph_metrics, :map, null: false
      add :knowledge_quality, :map, null: false
      add :consolidation_data, :map, null: false
      add :discovery_data, :map, null: false
      add :access_patterns, :map, null: false
      add :verification_status, :text, null: false, default: "unverified"
      add :indexing_status, :text, null: false, default: "pending"
      add :taxonomy_path, {:array, :text}, null: false, default: []
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:thunderblock_knowledge_nodes, [:embedding_vector_ids],
             name: "knowledge_nodes_embeddings_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:memory_record_ids],
             name: "knowledge_nodes_memories_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:taxonomy_path],
             name: "knowledge_nodes_taxonomy_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:relationship_data],
             name: "knowledge_nodes_relationships_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:source_domains],
             name: "knowledge_nodes_sources_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:semantic_tags],
             name: "knowledge_nodes_tags_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:aliases],
             name: "knowledge_nodes_aliases_idx",
             using: :gin
           )

    create index(:thunderblock_knowledge_nodes, [:indexing_status],
             name: "knowledge_nodes_indexing_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:confidence_level, :evidence_strength],
             name: "knowledge_nodes_quality_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:verification_status, :centrality_score],
             name: "knowledge_nodes_verification_idx"
           )

    create index(:thunderblock_knowledge_nodes, [:node_type, :knowledge_domain],
             name: "knowledge_nodes_type_domain_idx"
           )

    create unique_index(:thunderblock_knowledge_nodes, [:title, :knowledge_domain],
             name: "thunderblock_knowledge_nodes_unique_title_domain_index"
           )
  end

  def down do
    drop_if_exists unique_index(:thunderblock_knowledge_nodes, [:title, :knowledge_domain],
                     name: "thunderblock_knowledge_nodes_unique_title_domain_index"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:node_type, :knowledge_domain],
                     name: "knowledge_nodes_type_domain_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:verification_status, :centrality_score],
                     name: "knowledge_nodes_verification_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:confidence_level, :evidence_strength],
                     name: "knowledge_nodes_quality_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, [:indexing_status],
                     name: "knowledge_nodes_indexing_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (aliases)"],
                     name: "knowledge_nodes_aliases_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (semantic_tags)"],
                     name: "knowledge_nodes_tags_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (source_domains)"],
                     name: "knowledge_nodes_sources_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (relationship_data)"],
                     name: "knowledge_nodes_relationships_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (taxonomy_path)"],
                     name: "knowledge_nodes_taxonomy_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (memory_record_ids)"],
                     name: "knowledge_nodes_memories_idx"
                   )

    drop_if_exists index(:thunderblock_knowledge_nodes, ["USING GIN (embedding_vector_ids)"],
                     name: "knowledge_nodes_embeddings_idx"
                   )

    drop table(:thunderblock_knowledge_nodes)
  end
end
