defmodule Thunderline.Repo.Migrations.PrismTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prism_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_id, :uuid, null: false
      add :to_id, :uuid, null: false
      add :relation_type, :text, null: false, default: "next"
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:prism_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:prism_edges) do
      modify :from_id,
             references(:prism_nodes, column: :id, name: "prism_edges_from_id_fkey", type: :uuid)

      modify :to_id,
             references(:prism_nodes, column: :id, name: "prism_edges_to_id_fkey", type: :uuid)
    end

    alter table(:prism_nodes) do
      add :pac_id, :text, null: false
      add :iteration, :bigint, null: false
      add :chosen_model, :text, null: false
      add :model_probabilities, :map, default: %{}
      add :model_distances, :map, default: %{}
      add :meta, :map, default: %{}
      add :timestamp, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:prism_nodes) do
      remove :updated_at
      remove :inserted_at
      remove :timestamp
      remove :meta
      remove :model_distances
      remove :model_probabilities
      remove :chosen_model
      remove :iteration
      remove :pac_id
    end

    drop constraint(:prism_edges, "prism_edges_from_id_fkey")

    drop constraint(:prism_edges, "prism_edges_to_id_fkey")

    alter table(:prism_edges) do
      modify :to_id, :uuid
      modify :from_id, :uuid
    end

    drop table(:prism_nodes)

    drop table(:prism_edges)
  end
end
