defmodule Thunderline.Repo.Migrations.AddThundercoreThunderwall do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tick_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tick_id, :bigint, null: false
      add :tick_type, :text, null: false, default: "system"
      add :timestamp, :utc_datetime_usec, null: false
      add :monotonic_ns, :bigint, null: false
      add :epoch_ms, :bigint, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tick_states, [:tick_id, :tick_type],
             name: "tick_states_unique_tick_index"
           )

    create table(:identity_kernels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kernel_id, :uuid, null: false
      add :seed, :binary, null: false
      add :created_at_tick, :bigint
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lineage_id,
          references(:identity_kernels,
            column: :id,
            name: "identity_kernels_lineage_id_fkey",
            type: :uuid
          )
    end

    create unique_index(:identity_kernels, [:kernel_id],
             name: "identity_kernels_unique_kernel_id_index"
           )

    create table(:decay_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :text, null: false
      add :decay_reason, :text, null: false, default: "ttl_expired"
      add :snapshot, :map
      add :decayed_at_tick, :bigint
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:archive_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :text, null: false
      add :archive_reason, :text, null: false, default: "system"
      add :snapshot, :map, null: false
      add :archived_at_tick, :bigint
      add :retention_days, :bigint
      add :tags, {:array, :text}, default: []
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:archive_entries, [:resource_type, :resource_id],
             name: "archive_entries_unique_archive_index"
           )
  end

  def down do
    drop_if_exists unique_index(:archive_entries, [:resource_type, :resource_id],
                     name: "archive_entries_unique_archive_index"
                   )

    drop table(:archive_entries)

    drop table(:decay_records)

    drop_if_exists unique_index(:identity_kernels, [:kernel_id],
                     name: "identity_kernels_unique_kernel_id_index"
                   )

    drop constraint(:identity_kernels, "identity_kernels_lineage_id_fkey")

    drop table(:identity_kernels)

    drop_if_exists unique_index(:tick_states, [:tick_id, :tick_type],
                     name: "tick_states_unique_tick_index"
                   )

    drop table(:tick_states)
  end
end
