defmodule Thunderline.Repo.Migrations.AddThunderlineEvents do
  @moduledoc """
  Creates thunderline_events table for AshEvents tracking.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and modified to create the table.
  """

  use Ecto.Migration

  def up do
    create table(:thunderline_events, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :action_type, :text, null: false
      add :record_id, :uuid, null: false
      add :data, :map, null: false, default: %{}
      add :version, :bigint, null: false
      add :domain, :text, null: false, default: "unknown"
      add :metadata, :map, default: %{}
      add :operation_type, :text
      add :criticality, :text, default: "medium"
      add :correlation_id, :uuid
      add :agent_id, :uuid
      add :user_id, :uuid
      add :replay_required, :boolean, default: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create index(:thunderline_events, [:resource])
    create index(:thunderline_events, [:action_type])
    create index(:thunderline_events, [:record_id])
    create index(:thunderline_events, [:occurred_at])
    create index(:thunderline_events, [:domain])
  end

  def down do
    drop table(:thunderline_events)
  end
end
