defmodule Thunderline.Repo.Migrations.AddIntrinsicRewardToProbeRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:probe_runs) do
      add :intrinsic_reward, :decimal
    end

    drop constraint(:embedding_vectors, "embedding_vectors_knowledge_node_id_fkey")

    alter table(:embedding_vectors) do
      modify :knowledge_node_id,
             references(:thunderblock_knowledge_nodes,
               column: :id,
               name: "embedding_vectors_knowledge_node_id_fkey",
               type: :uuid
             )
    end
  end

  def down do
    drop constraint(:embedding_vectors, "embedding_vectors_knowledge_node_id_fkey")

    alter table(:embedding_vectors) do
      modify :knowledge_node_id,
             references(:thunderblock_knowledge_nodes,
               column: :id,
               name: "embedding_vectors_knowledge_node_id_fkey",
               type: :uuid
             )
    end

    alter table(:probe_runs) do
      remove :intrinsic_reward
    end
  end
end
