defmodule Thunderline.Repo.Migrations.CreateZonesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:zones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :q, :bigint, null: false
      add :r, :bigint, null: false
      add :aspect, :text, null: false, default: "neutral"
      add :entropy, :decimal, null: false, default: "0.0"
      add :energy_level, :decimal, null: false, default: "0.5"
      add :agent_count, :bigint, null: false, default: 0
      add :max_agents, :bigint, null: false, default: 10
      add :properties, :map, null: false, default: %{}
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:zone_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :description, :text, null: false
      add :event_data, :map, null: false, default: %{}
      add :severity, :text, null: false, default: "info"
      add :coordinates, :map, null: false
      add :impact_radius, :bigint, null: false, default: 0
      add :duration_ms, :bigint
      add :was_predicted, :boolean, null: false, default: false
      add :prediction_accuracy, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :zone_id,
          references(:zones, column: :id, name: "zone_events_zone_id_fkey", type: :uuid),
          null: false

      add :agent_id, :uuid

      add :triggered_by_action_id, :uuid
    end

    create table(:thundergrid_zone_boundaries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :boundary_name, :text, null: false
      add :boundary_type, :text, null: false, default: "standard"
      add :geometry_type, :text, null: false, default: "line"
      add :boundary_points, {:array, :map}, null: false, default: []
      add :permeability, :decimal, null: false, default: "1.0", precision: 3, scale: 2
      add :crossing_rules, :map, null: false
      add :directional_properties, :map, null: false
      add :security_level, :bigint, null: false, default: 0
      add :monitoring_enabled, :boolean, null: false, default: false
      add :crossing_history, :map, null: false
      add :environmental_effects, :map, null: false
      add :maintenance_status, :text, null: false, default: "stable"
      add :last_maintenance, :utc_datetime
      add :zone_id, :uuid, null: false
      add :adjacent_zone_id, :uuid
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:thundergrid_zone_boundaries, [:maintenance_status])

    create index(:thundergrid_zone_boundaries, [:monitoring_enabled])

    create index(:thundergrid_zone_boundaries, [:security_level])

    create index(:thundergrid_zone_boundaries, [:boundary_type])

    create index(:thundergrid_zone_boundaries, [:zone_id, :adjacent_zone_id], unique: true)

    create unique_index(:thundergrid_zone_boundaries, [:zone_id, :adjacent_zone_id],
             name: "thundergrid_zone_boundaries_unique_zone_boundary_index"
           )

    create table(:thundergrid_spatial_coordinates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :hex_q, :bigint, null: false
      add :hex_r, :bigint, null: false
      add :hex_s, :bigint, null: false
      add :sub_hex_x, :decimal, null: false, default: "0.0", precision: 10, scale: 6
      add :sub_hex_y, :decimal, null: false, default: "0.0", precision: 10, scale: 6
      add :elevation, :decimal, null: false, default: "0.0", precision: 10, scale: 3
      add :coordinate_type, :text, null: false, default: "position"
      add :occupancy_status, :text, null: false, default: "vacant"
      add :occupant_id, :uuid
      add :occupant_type, :text
      add :properties, :map, null: false
      add :navigation_data, :map, null: false
      add :last_accessed, :utc_datetime
      add :zone_id, :uuid
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:thundergrid_spatial_coordinates, [:last_accessed])

    create index(:thundergrid_spatial_coordinates, [:coordinate_type])

    create index(:thundergrid_spatial_coordinates, [:occupancy_status])

    create index(:thundergrid_spatial_coordinates, [:occupant_id])

    create index(:thundergrid_spatial_coordinates, [:zone_id])

    create index(:thundergrid_spatial_coordinates, [:hex_q, :hex_r, :hex_s])

    create index(:thundergrid_spatial_coordinates, [:hex_q, :hex_r])

    create unique_index(
             :thundergrid_spatial_coordinates,
             [:hex_q, :hex_r, :sub_hex_x, :sub_hex_y, :elevation],
             name: "thundergrid_spatial_coordinates_unique_hex_position_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :thundergrid_spatial_coordinates,
                     [:hex_q, :hex_r, :sub_hex_x, :sub_hex_y, :elevation],
                     name: "thundergrid_spatial_coordinates_unique_hex_position_index"
                   )

    drop_if_exists index(:thundergrid_spatial_coordinates, [:hex_q, :hex_r])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:hex_q, :hex_r, :hex_s])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:zone_id])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:occupant_id])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:occupancy_status])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:coordinate_type])

    drop_if_exists index(:thundergrid_spatial_coordinates, [:last_accessed])

    drop table(:thundergrid_spatial_coordinates)

    drop_if_exists unique_index(:thundergrid_zone_boundaries, [:zone_id, :adjacent_zone_id],
                     name: "thundergrid_zone_boundaries_unique_zone_boundary_index"
                   )

    drop_if_exists index(:thundergrid_zone_boundaries, [:zone_id, :adjacent_zone_id])

    drop_if_exists index(:thundergrid_zone_boundaries, [:boundary_type])

    drop_if_exists index(:thundergrid_zone_boundaries, [:security_level])

    drop_if_exists index(:thundergrid_zone_boundaries, [:monitoring_enabled])

    drop_if_exists index(:thundergrid_zone_boundaries, [:maintenance_status])

    drop table(:thundergrid_zone_boundaries)

    drop table(:zone_events)

    drop table(:zones)
  end
end
