defmodule Thunderline.Repo.Migrations.AddApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:thunderbit_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category_id, :text, null: false
      add :ontology_path, {:array, :text}, default: []
      add :role, :text, null: false
      add :description, :text
      add :inputs, :map, default: %{}
      add :outputs, :map, default: %{}
      add :capabilities, {:array, :text}, default: []
      add :forbidden, {:array, :text}, default: []
      add :can_link_to, {:array, :text}, default: []
      add :can_receive_from, {:array, :text}, default: []
      add :composition_mode, :text, default: "serial"
      add :required_maxims, {:array, :text}, default: []
      add :forbidden_maxims, {:array, :text}, default: []
      add :geometry, :map, default: %{}
      add :examples, {:array, :text}, default: []
      add :enabled, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thunderbit_definitions, [:category_id],
             name: "thunderbit_definitions_unique_category_id_index"
           )

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :name, :text
      add :scopes, {:array, :text}, default: []
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, references(:users, column: :id, name: "api_keys_user_id_fkey", type: :uuid),
        null: false
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop_if_exists unique_index(:thunderbit_definitions, [:category_id],
                     name: "thunderbit_definitions_unique_category_id_index"
                   )

    drop table(:thunderbit_definitions)
  end
end
