defmodule Thunderline.Repo.Migrations.AddThunderlinkNodeRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:thunderlink_node_group_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_id, :uuid, null: false, primary_key: true
      add :group_id, :uuid, null: false, primary_key: true
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlink_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderlink_node_group_memberships) do
      modify :node_id,
             references(:thunderlink_nodes,
               column: :id,
               name: "thunderlink_node_group_memberships_node_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    alter table(:thunderlink_nodes) do
      add :name, :text, null: false
      add :role, :text, null: false, default: "worker"
      add :domain, :text, null: false, default: "thunderlink"
      add :status, :text, null: false, default: "disconnected"
      add :cluster_type, :text, null: false, default: "in_cluster"
      add :hotline_peer_id, :text
      add :did, :text
      add :last_seen_at, :utc_datetime_usec
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thunderlink_nodes, [:name], name: "thunderlink_nodes_unique_name_index")

    create table(:thunderlink_link_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :node_id,
          references(:thunderlink_nodes,
            column: :id,
            name: "thunderlink_link_sessions_node_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :remote_node_id,
          references(:thunderlink_nodes,
            column: :id,
            name: "thunderlink_link_sessions_remote_node_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :session_type, :text, null: false, default: "cluster"
      add :status, :text, null: false, default: "establishing"
      add :weight, :float, default: 1.0
      add :latency_ms, :bigint
      add :bandwidth_mbps, :float
      add :established_at, :utc_datetime_usec
      add :last_activity_at, :utc_datetime_usec
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:thunderlink_node_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:thunderlink_node_group_memberships) do
      modify :group_id,
             references(:thunderlink_node_groups,
               column: :id,
               name: "thunderlink_node_group_memberships_group_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    create unique_index(:thunderlink_node_group_memberships, [:node_id, :group_id],
             name: "thunderlink_node_group_memberships_unique_membership_index"
           )

    alter table(:thunderlink_node_groups) do
      add :name, :text, null: false
      add :group_type, :text, null: false, default: "custom"

      add :parent_group_id,
          references(:thunderlink_node_groups,
            column: :id,
            name: "thunderlink_node_groups_parent_group_id_fkey",
            type: :uuid
          )

      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thunderlink_node_groups, [:name],
             name: "thunderlink_node_groups_unique_name_index"
           )

    create table(:thunderlink_node_capabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :node_id,
          references(:thunderlink_nodes,
            column: :id,
            name: "thunderlink_node_capabilities_node_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :capability_key, :text, null: false
      add :capability_value, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:thunderlink_node_capabilities, [:node_id, :capability_key],
             name: "thunderlink_node_capabilities_unique_capability_per_node_index"
           )

    create table(:thunderlink_heartbeats, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :node_id,
          references(:thunderlink_nodes,
            column: :id,
            name: "thunderlink_heartbeats_node_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :status, :text, null: false
      add :cpu_load, :float
      add :mem_used_mb, :bigint
      add :latency_ms, :bigint
      add :meta, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:thunderlink_heartbeats, "thunderlink_heartbeats_node_id_fkey")

    drop table(:thunderlink_heartbeats)

    drop_if_exists unique_index(:thunderlink_node_capabilities, [:node_id, :capability_key],
                     name: "thunderlink_node_capabilities_unique_capability_per_node_index"
                   )

    drop constraint(:thunderlink_node_capabilities, "thunderlink_node_capabilities_node_id_fkey")

    drop table(:thunderlink_node_capabilities)

    drop_if_exists unique_index(:thunderlink_node_groups, [:name],
                     name: "thunderlink_node_groups_unique_name_index"
                   )

    drop constraint(:thunderlink_node_groups, "thunderlink_node_groups_parent_group_id_fkey")

    alter table(:thunderlink_node_groups) do
      remove :updated_at
      remove :inserted_at
      remove :meta
      remove :parent_group_id
      remove :group_type
      remove :name
    end

    drop_if_exists unique_index(:thunderlink_node_group_memberships, [:node_id, :group_id],
                     name: "thunderlink_node_group_memberships_unique_membership_index"
                   )

    drop constraint(
           :thunderlink_node_group_memberships,
           "thunderlink_node_group_memberships_group_id_fkey"
         )

    alter table(:thunderlink_node_group_memberships) do
      modify :group_id, :uuid
    end

    drop table(:thunderlink_node_groups)

    drop constraint(:thunderlink_link_sessions, "thunderlink_link_sessions_node_id_fkey")

    drop constraint(:thunderlink_link_sessions, "thunderlink_link_sessions_remote_node_id_fkey")

    drop table(:thunderlink_link_sessions)

    drop_if_exists unique_index(:thunderlink_nodes, [:name],
                     name: "thunderlink_nodes_unique_name_index"
                   )

    alter table(:thunderlink_nodes) do
      remove :updated_at
      remove :inserted_at
      remove :meta
      remove :last_seen_at
      remove :did
      remove :hotline_peer_id
      remove :cluster_type
      remove :status
      remove :domain
      remove :role
      remove :name
    end

    drop constraint(
           :thunderlink_node_group_memberships,
           "thunderlink_node_group_memberships_node_id_fkey"
         )

    alter table(:thunderlink_node_group_memberships) do
      modify :node_id, :uuid
    end

    drop table(:thunderlink_nodes)

    drop table(:thunderlink_node_group_memberships)
  end
end
